### ISSUE TITLE
Need to improve extremely slow (1min) long "unit" tests

### ISSUE THREAD

**Issue by Eilon** [aspnet/Caching#106]
These two are super slow to run:

1. **30sec** [GcNotificationTests.CallbackInvokedMultipleTimes](https://github.com/aspnet/Caching/blob/dev/test/Microsoft.Framework.Caching.Memory.Tests/GcNotificationTests.cs#L28-L59)
2. **1min** [MemoryCacheSetAndRemoveTests.SetOverwritesAndInvokesCallbacks](https://github.com/aspnet/Caching/blob/dev/test/Microsoft.Framework.Caching.Memory.Tests/MemoryCacheSetAndRemoveTests.cs#L85-L131)

These take way, waaay too long.

**Comment by Tratcher** [comment]
FYI: These kept getting lengthened because slow CI machines would cause timeouts for the positive tests (Assert.True). The negative tests (Assert.False) don't actually need timeouts that long.

Also https://github.com/aspnet/Caching/pull/95

**Comment by muratg** [comment]
See https://github.com/aspnet/Caching/pull/95/files

**Comment by muratg** [comment]
Putting this in RC1 for now.

**Comment by muratg** [comment]
@BrennanConroy Please adjust the timeouts on the negative tests

**Comment by BrennanConroy** [comment]
Looks like the GCNotificationTest was fixed by #120

**Comment by BrennanConroy** [comment]
834385ee7495571550b2f0eb2ffd2c7fe6725dbe
