### ISSUE TITLE
Is Caching.Abstractions the right place to put IExpirationTrigger?

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Caching#108]
Spoke to @davidfowl and @lodejard offline. Their consensus is that putting it in Caching.Abstractions is wrong layering. There doesn't seem to be an alternate place to move it to at this point.

**Comment by lodejard** [comment]
Move to `Microsoft.Framework.Primatives` and rename to `IChangeToken`

Also move `Microsoft.Framework.Primatives` to a different repo than HttpAbstractions.

**Comment by pranavkm** [comment]
We could put `Microsoft.Framework.Primitives` in Common (seems common enough). Alternatively @Eilon, could you create a new repo for this?

**Comment by Tratcher** [comment]
That makes sense for FileProviders, but doesn't match the design/usage in memory cache. IExpirationTriggers are used to evict something from the cache, they don't specify why. IChangeToken hardcodes the `why`.  Note the only other implementation of IExpirationTrigger is CancellationTokenTrigger.

Would it make more sense to separate these concepts again and provide a bridge?

**Comment by lodejard** [comment]
Nah - things are being expired because something has changed. Bridge is just an extra layer that forces the user to find the adapter between them.

Common looks like a perfect location.

**Comment by pranavkm** [comment]
Self assigning for beta8
