### ISSUE TITLE
Default expiration times / cache behavior with empty options on set

### ISSUE THREAD

**Issue by sunsided** [aspnet/Caching#113]
Is there any default value or expected behavior on expiration times? I feel like I'm missing something critical, but isn't `new DistributedCacheEntryOptions()` on a `Set` basically a guaranteed fuckup with a distributed cache if the client process dies midway?

**Comment by Tratcher** [comment]
With empty options the cache is free to remove the least recently used items as it sees fit. This is an implementation detail of the storage provider as well as the cache implementation.

**Comment by sunsided** [comment]
Okay (and thanks). That's fine by me. Is there a reason why this isn't a required configuration parameter?

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
