### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/Caching#114]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by pranavkm** [comment]
b0173c7be7265707f7b70e0adf7ee0abd4ffea39
