### ISSUE TITLE
Why use caching.redis?

### ISSUE THREAD

**Issue by simonpbond** [aspnet/Caching#117]
Why should I use microsoft.framework.caching.redis (that has a dependency on stackexchange.redis) instead of just using the functionality already available in stackexchange.redis?

**Comment by Tratcher** [comment]
Because it implements IDistributedCache and can be plugged into other places in the framework like Session.

**Comment by simonpbond** [comment]
What is the difference between using MemoryCache and IDistributed cache.
Does MemoryCache refer to sessions? and can MemoryCache be used with Redis (as IDistributedCache can)?

I was under the impression (with limited knowledge) that MemoryCache refers to the local memory of the server, whereas IDistributedCache allows moving the cache off the server and on to Redis (or another store), which would make me think MemoryCache wouldn't use Redis.

Can you clear this up for me? Thanks.

**Comment by Tratcher** [comment]
"I was under the impression (with limited knowledge) that MemoryCache refers to the local memory of the server, whereas IDistributedCache allows moving the cache off the server and on to Redis (or another store), which would make me think MemoryCache wouldn't use Redis."
That is all correct. Session can use MemoryCache to store data locally or Redis to store it remotely.

**Comment by simonpbond** [comment]
By injecting both:

services.AddSingleton<IMemoryCache, MemoryCache>();
services.AddSingleton<IDistributedCache, RedisCache>();

I have the option to store data in local memory or in Redis.

However, does ASP/MVC have any session data that is automatically stored when doing this (I'm thinking something like the session state from webforms etc.)?

Or is there no automatic session data used in ASP/MVC and it will only ever be my own custom sessions data?

**Comment by simonpbond** [comment]
Above code should read:

    services.AddSingleton<IMemoryCache, MemoryCache>();
    services.AddSingleton<IDistributedCache, RedisCache>();

**Comment by Tratcher** [comment]
Session is implemented here: https://github.com/aspnet/session. MVC's temp data feature uses session, but I'm not aware of anything else that uses it by default.

**Comment by simonpbond** [comment]
Sorry, just to close off, doing the above will only provide me the ability to store my own custom data in cache (either in memory, or redis) and will not affect sessions as is?

Thanks again

**Comment by Tratcher** [comment]
Session will pick up IDistributedCache from services, so yes you will affect it. Unless you make it a Transient service so they don't share.

**Comment by simonpbond** [comment]
Thanks for clearing everything up. Appreciated.
