### ISSUE TITLE
Redis is not supported for .netCore, any plans?

### ISSUE THREAD

**Issue by eashi** [aspnet/Caching#121]
I wanted to use Redis with .net core, but it is not supported. Will this be supported anytime in the future?

![rediscore50](https://cloud.githubusercontent.com/assets/2030617/11048941/daed1836-878e-11e5-9a97-7a883fdd5f43.JPG)

**Comment by Tratcher** [comment]
We're waiting on support from StackExchange.Redis. @rustd?

**Comment by rustd** [comment]
refer to https://github.com/StackExchange/StackExchange.Redis/issues/202

**Comment by muratg** [comment]
@eashi closing this one as the work is tracked on StackExchange repo.

**Comment by rustd** [comment]
There is a version of SE.Redis which works for .NET Core
https://www.nuget.org/packages/StackExchange.Redis/1.1.0-alpha1
https://www.nuget.org/packages/StackExchange.Redis.StrongName/1.1.0-alpha1

/cc @Tratcher

**Comment by muratg** [comment]
@rustd What's the work on our end?

**Comment by rustd** [comment]
Update Microsoft.Extensions.Caching.Redis to take a dependency on this package so users can use ASP.NET 5 Caching with Redis on .NET Core
 https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Redis/project.json

**Comment by muratg** [comment]
If Nick gets SE.Redis RTM'd, we'll do this.

**Comment by atrauzzi** [comment]
Would anyone happen to know when we can expect to see this ready for use?

**Comment by Tratcher** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/1.1.0-preview1-final

**Comment by atrauzzi** [comment]
@Tratcher - Are there any special steps I have to take to get this version of the package into my project?

When I add `"Microsoft.Extensions.Caching.Redis": "1.1.0-preview1-final",`, my references show as being unable to resolve it.

**Comment by atrauzzi** [comment]
Ah, nevermind, looks like I needed to add this to my `Nuget.Config`:

`<add key="aspnet-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />`

**Comment by Tratcher** [comment]
that shouldn't have been required... that package isn't even on the aspnetcore-dev feed, it's only on nuget.org.

**Comment by atrauzzi** [comment]
@Tratcher - Odd.  The only way I could keep visual studio from barking at me was by adding that feed.  I'll be honest, the nuget package stuff isn't always the most predictable.  So I might have missed something.

Is there anything you'd like me to check, just to be certain?

**Comment by muratg** [comment]
@atrauzzi does using cmdline (i.e. `dotnet restore`) fail as well? (when you only have nuget.org in your nuget.config.)

**Comment by atrauzzi** [comment]
Yeah, it did actually.  Guess it's just a VS thing?

**Comment by muratg** [comment]
Yeah, I guess. @sayedihashimi thoughts? It looks like restore is failing on VS, but working fine on cmd line...

**Comment by atrauzzi** [comment]
It's not a big deal for me if I can work around it, I understand that there's probably going to be a lot of shifting as msbuild is brought back into view.

**Comment by LonghronShen** [comment]
Hi there, I have one question. Why the rel/1.0.2 branch still use StackExchange.Redis.StrongName (>= 1.0.333) dependency rather than StackExchange.Redis.StrongName (>= 1.1.605) which rel/1.1.x has? And since rel/1.1.x supports .NET Standard platform, why not make LTS branch support it?
