### ISSUE TITLE
Redis Mac OSX Error

### ISSUE THREAD

**Issue by ngonzalezromero** [aspnet/Caching#124]
I have the following error when trying to connect to networks from Mac OSX (Mono 4.2 ,dnx rc-1-final)

 An unhandled exception has occurred: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
      StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
        at StackExchange.Redis.ConnectionMultiplexer.Connect (System.String configuration, System.IO.TextWriter log) <0x6ef60f0 + 0x00113> in <filename unknown>:0 

in Windows 10 I have no problem

**Comment by ngonzalezromero** [comment]
any help? @davidfowl

**Comment by davidfowl** [comment]
Try mono 4.0.5

**Comment by ngonzalezromero** [comment]
i did it..same error

https://github.com/StackExchange/StackExchange.Redis/issues/233

**Comment by davidfowl** [comment]
Nothing you can do othe than report a mono bug

**Comment by muratg** [comment]
Do you have the same issue on CoreCLR @ngonzalezromero?

**Comment by ngonzalezromero** [comment]
Yes... same error.. but i found that is a error of corefx 
https://github.com/dotnet/corefx/issues/4733
https://github.com/dotnet/corefx/issues/4588

**Comment by muratg** [comment]
Thanks @ngonzalezromero! So it's already tracked on CoreFX.  Closing this one as external, but file another issue if this continues to be broken after CoreFX issues are closed.
