### ISSUE TITLE
Redis cache does not implement Microsoft.Extensions.Caching.Distributed.IDistributedCache

### ISSUE THREAD

**Issue by joaquin-corchero** [aspnet/Caching#128]
Good morning,

I was trying to implement Sessions and Caching using Redis.

The framework is dnx451 and the versions of the packages are:
"Microsoft.Framework.Caching.Redis": "1.0.0-rc1-15658",
"Microsoft.AspNet.Session": "1.0.0-rc1-final"

RedisCache implements the interface Microsoft.Framework.Caching.Distributed.IDistributedCache but in order to use RedisCache for session, it needs to implement Microsoft.Extensions.Caching.Distributed.IDistributedCache which has a very similar contract, but not exactly the same.

In order to acomplish that, I have implemented my own class as follows:
public class OwnRedisCache : RedisCache, IDistributedCache
    {
        public OwnRedisCache(IOptions<RedisCacheOptions> optionsAccessor) : base(optionsAccessor)
        {
        }

        public void Set(string key, byte[] value, DistributedCacheEntryOptions options)
        {
            base.Set(key, value, new Microsoft.Framework.Caching.Distributed.DistributedCacheEntryOptions());
        }

        public Task SetAsync(string key, byte[] value, DistributedCacheEntryOptions options)
        {
            return base.SetAsync(key, value, new Microsoft.Framework.Caching.Distributed.DistributedCacheEntryOptions());
        }
    }

Is it possible or are you planning to modify the RedisCache class so it implements both interfaces?

Code to a full implementation can be found on https://github.com/joaquin-corchero/MVC6RedisSessionAndCache

Cheers

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/77
