### ISSUE TITLE
Shouldn't there be a Disconnect method for IDistributedCache ?

### ISSUE THREAD

**Issue by basitanwer** [aspnet/Caching#131]
For any store there should be a disconnect function taking full responsibility of 

 - Securely closing sockets connections
 - Disposing resources.

**Comment by muratg** [comment]
@kichalla Do you remember why we don't have Disconnect?  Per another issue, we don't even use Connect often in the samples so perhaps this is not required?

**Comment by muratg** [comment]
Just talked to @lodejard. Triaging this for RC2.

**Comment by Eilon** [comment]
@lodejard putting on your plate.
