### ISSUE TITLE
Add Doc Comments to IDistributedCache and its Implementations

### ISSUE THREAD

**Issue by ardalis** [aspnet/Caching#133]
They exist for IMemoryCache but not IDistributedCache. Be sure to say when it's required to call Connect and/or ConnectAsync, since most of the samples never call this method.

**Comment by muratg** [comment]
Agreed.

@Eilon Should we have another sweep at the API docs in RC2?

**Comment by Eilon** [comment]
@muratg at this point I would do repo-specific sweeps. The only sweep we did so far was based on what the templates use, and that hasn't changed much.

**Comment by muratg** [comment]
Cool.  BTW for this particular issue, @kichalla will be removing `Connect` and `ConnectAsync` methods from the interface. They are really just convenience methods for Redis cache (and will be private for that implementation.)

@kichalla please close this issue once that change is done.

**Comment by muratg** [comment]
Methods removed, so closing this one.
