### ISSUE TITLE
Maximum Key Length on Primary Key

### ISSUE THREAD

**Issue by Gonkers** [aspnet/Caching#146]
The ID on the caching table is nvarchar(900); with a maximum key length of 900 bytes won't the ID column have a max size of 1800 byes?

When executing the create table statement, SQL Server does generate a warning.
`Warning! The maximum key length is 900 bytes. The index 'pk_Id' has maximum length of 1800 bytes. For some combination of large values, the insert/update operation will fail.`

**Comment by muratg** [comment]
Per [this article](https://msdn.microsoft.com/en-us/library/ms186939.aspx?f=255&MSPPError=-2147217396) the actual size in byte would be 900*2+2 == 1802 bytes.

Where do you hit this issue?  When using sqlconfig?

@kichalla Any ideas?

**Comment by Gonkers** [comment]
I was investigating how the code worked. I received the warning when I ran the formatted `CREATE TABLE` SQL command in SQL Server Management Studio.

`Caching/src/dotnet-sql-cache/SqlQueries.cs`
```
        private const string CreateTableFormat = "CREATE TABLE {0}(" +
            // add collation to the key column to make it case-sensitive
            "Id nvarchar(900) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL, " +
            "Value varbinary(MAX) NOT NULL, " +
            "ExpiresAtTime datetimeoffset NOT NULL, " +
            "SlidingExpirationInSeconds bigint NULL," +
            "AbsoluteExpiration datetimeoffset NULL, " +
            "CONSTRAINT pk_Id PRIMARY KEY (Id))";
```

**Comment by muratg** [comment]
Assigning to @kichalla for investigation
