### ISSUE TITLE
Need doc comments on options properties

### ISSUE THREAD

**Issue by Eilon** [aspnet/Caching#150]
E.g. https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Redis/RedisCacheOptions.cs

**Comment by muratg** [comment]
@HaoK could you have a look?

Also, didn't you remove IOptions, or is it still WIP?

**Comment by HaoK** [comment]
Still making sure the pattern is acceptable. Once it's been agreed on I will update all the repos this week.

**Comment by HaoK** [comment]
13f22e8a3d5747b9ab5ff43205cabc2f988bc9d7
