### ISSUE TITLE
Caching APIs for adding services need to take in config lambda

### ISSUE THREAD

**Issue by Eilon** [aspnet/Caching#152]
The various `services.AddXYZCaching()` methods are all parameterless - they need to take in a configuration lambda. Right now you have to call `services.Configure<XYZCacheOptions>(options => { options.FooSetting = "value"; });` to configure them.

E.g.:
* https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Redis/RedisCacheServicesExtensions.cs#L22
* https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCacheServicesExtensions.cs#L20

Note: The SQL Server services extension method does the right thing: https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.SqlServer/SqlServerCacheExtensions.cs#L23-L25

@divega this is what I mentioned to you yesterday.

**Comment by Eilon** [comment]
@divega @HaoK @lodejard @davidfowl @DamianEdwards I wonder if we have more inconsistencies around? I presume we need to have someone take a look at all our services extension methods?

**Comment by divega** [comment]
Adding @rynowak who last time did a great job getting all these ducks in a line :smile:

**Comment by rynowak** [comment]
I'm here! Yeah, we should take a look. I seem to recall identifying 3-4 things that needed to change before... I'll see if I can dig up that mail. Wouldn't hurt to do a fresh pass too. I'll follow up on that and open issues.

**Comment by muratg** [comment]
@rynowak Did you get a chance to look into this?

**Comment by Eilon** [comment]
@muratg we have a meeting on this tomorrow, I'll add you to it.

**Comment by javiercn** [comment]
@eilon I'm already covering this as part of https://github.com/aspnet/Caching/pull/156/files. Se might need to add options to inmemory

**Comment by javiercn** [comment]
Actually, inmemory needs the options flavor. I've been looking at this specifically on all the repositories where I've normalized the service collection extensions.

For inmemory specifically, I'm not sure what the value for the IClock implementation would be. I believe that fits better as a service.

**Comment by javiercn** [comment]
a6c044c1590b16c98df1cc6d01eca1140a86ee99
