### ISSUE TITLE
Manual output cache busting?

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/Caching#154]
Is there any way to clear/flush/remove OutputCache? 

I have html fragments in a partial view that uses the output cache like so

```
 <cache vary-by="@Util.SomeID" expires-after="@TimeSpan.FromHours(1)">
     <div>some content</div>
 </cache>
```

In the event that I need the content to be updated before the expiration of the cache, how do I go about busting the cache for that particular fragment (or the entire cache, if necessary) ?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Mvc#4117
