### ISSUE TITLE
Distributed Memory Caching

### ISSUE THREAD

**Issue by klepeis** [aspnet/Caching#161]
The dev branch has a class for distributed memory caching.  I was just wondering if distributed memory caching is slated to make it out in the RTM release of vNext?  If it is not going to be in the RTM release:
1) Is this something that is just being thought about or is it definitely on the product road map?
2) Any ETA on when this will make it to release?

Thanks

**Comment by Tratcher** [comment]
`MemoryDistributedCache` right? That's just an implementation of `IDistributedCache` for use in non-distributed environments. It's primarily intended for local development and testing, but may also be used in single node deployments. Yes it will be included for RTM. The schedule is here: https://github.com/aspnet/Home/wiki/Roadmap

**Comment by klepeis** [comment]
Thanks.  The readme had this in it:

> Contains libraries for in-memory caching and distributed caching. Includes distributed cache implementations for in-memory, Microsoft SQL Server, and Redis.

The wording had me wondering if we would be getting distributed memory caching for a multi-node environment.

Thanks!
