### ISSUE TITLE
We should remove IMemoryCache.Remove

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Caching#162]
To remove entries the supported scenario is to add a token (like a CancellationTokenSource) in he options of the entry.

**Comment by sebastienros** [comment]
@lodejard Will confirm if necessary.

**Comment by Tratcher** [comment]
And IDistributedCache?

**Comment by lodejard** [comment]
Distributed cache and memory cache are different

**Comment by Eilon** [comment]
Though I think there is merit to this proposal, it would make IMemoryCache too difficult to use in the most common cases people are familiar with.

**Comment by Eilon** [comment]
(Plus, a massive API change.)

**Comment by sebastienros** [comment]
You terrorists !!!!
