### ISSUE TITLE
Key export / bulk remove / clear for MemoryCache

### ISSUE THREAD

**Issue by pebezo** [aspnet/Caching#187]
When it comes to working with the internal keys, the way MemoryCache / IMemoryCache works is too limiting. Yes, I can remove by key, but there are lot of scenarios where we need to remove items from the cache without knowing the exact keys. For these cases we would have to keep a copy of those keys in a separate list (extra RAM usage and maintenance) or go back to the database (if there is a copy of these keys in the database).

I understand that accessing the internal keys in the cache is problematic. What I'm suggesting is for the  MemoryCache to create a (new) list of the item keys in an atomic way. We could then iterate over this list and call `Remove()` if needed.

This would be an expensive operation, but it would happen infrequently, and we're willing to take the hit. Ideally, it would also have a lambda to allow us to return only the items we want, something like:

`cache.Extract<T>(p => ...);`
`cache.ExtractAll();`
`cache.RemoveAll(p => ...);`

Clearing all the keys should also be available. Currently we would have to destroy the cache object - not exactly easy when used from ASP.NET. 

Thanks.

**Comment by muratg** [comment]
@pebezo Thanks for the suggestion, although I think a public API like that would be a pit of failure. As this is a cache only, keys and their corresponding values could disappear under you. 

You could get this functionality by wrapping our cache. Basically store all the keys as you interact with a cache, and do whatever with them later.

**Comment by pebezo** [comment]
"keys and their corresponding values could disappear under you"

Even if the operation is atomic? MemoryCache is very useful for small datasets, but not having a way to get the keys back would more than likely force us to use Redis (which is an overkill for small sets)

http://redis.io/commands/KEYS

I would argue that asking people to wrap MemoryCache is an even deeper pit of failure. You'd be asking people to worry about lockign and concurrency - something MC already does, so basically duplicating all that logic.

**Comment by davidfowl** [comment]
@pebezo What's atomic?

**Comment by Tratcher** [comment]
Related:
https://github.com/aspnet/Caching/issues/96
https://github.com/aspnet/Caching/issues/155

**Comment by pebezo** [comment]
@davidfowl Wrapped around a "lock" like here:

https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L167

**Comment by pebezo** [comment]
Was `Compact()` intended to be public?

https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L350

It's not part of the interface:

https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Abstractions/IMemoryCache.cs

A RemoveAll() function would be very similar -- much simpler.

**Comment by muratg** [comment]
@pebezo 
> "keys and their corresponding values could disappear under you" 
 Even if the operation is atomic? MemoryCache is very useful for small datasets, but not having a way to get the keys back would more than likely force us to use Redis (which is an >overkill for small sets)  

Even if you get the names of all keys at once, some (or all) of them may be deleted by the time you want to use them.

**Comment by pebezo** [comment]
@muratg But that's the expect behavior with or without this feature. When you get (or remove) something out of the cache based on a key that element may or may not be in the cache: TryGetValue(). How does extracting a list of all the keys change any of that?

**Comment by emelhu** [comment]
My suggestion, idea:

Like CancellationToken at thread, we can attach a token object to cached object.
This can be common for a group of stored objects. :)

And when (for example) a user modify the source/origin of cached data, the AspNetCore program set a 'cancel' and when the MemoryCache make a cache-cleaning (or retrieve this cached object) drop this object with this token.

**Comment by emelhu** [comment]
I have been implemented the idea before: https://github.com/emelhu/MemoryCache_DropOutToken

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by ferrx** [comment]
> Even if you get the names of all keys at once, some (or all) of them may be deleted by the time you want to use them. @muratg 

You have given this guidance:

> You could get this functionality by wrapping our cache. Basically store all the keys as you interact with a cache, and do whatever with them later.

Wouldn't you face the same pitfall when using this strategy? How is pulling a list of stored keys, iterating over them, and calling `Remove()` safer than a `RemoveAll()`.. which I assume would be the same operation?

RemoveAll would face the same pitfall as a simple Remove (or bulk Remove calls), but would save API users the trouble of storing/managing keys.

**Comment by andrewgunn** [comment]
@muratg Not sure why you closed this issue without having a resolution in place or at least a plan for the future. I agree with @pebezo that this sort of functionality is lacking.

At best, I was hoping for a way to purge everything by doing a partial match on a key. To elaborate, `string.Contains/StartsWith/EndsWith` would suffice, but Regex support would be the icing on the cake. 

At worst, I'd expect a clean way of purging the cache, however, I'm concerned that this approach would be too extreme for scenarios like this.

**My use case:**
I want to cache data from a store that will ultimately be returned from an API endpoint in a list format (e.g. `/customers/:customerId/orders GET`). Sounds simple, but what about when you factor in things like filters, paging, and sorting. When an order is added to a customer, I'd obviously need to purge any cache items associated with that customer, but I don't know all of the cache keys (without storing them, which is a viable option but seem a bit overkill to me). I know part of the cache key; the customer ID, and I know the format of the cache key; `/customers/1/orders?pageNumber=2`, so why can't I have my cake and eat it?

**Comment by plaisted** [comment]
Any suggestions on how to handle the use case @andrewgunn stated? This seems like a very common use case for web applications.  An event occurs (eg. updating customer N) that will invalidate cache results for related data (eg. orders) so we want to clear all the associated cached data.

**Comment by Tratcher** [comment]
@plaisted Attaching a IChangeToken to the group of entries you want to remove is the recommendation for group cleanup.

**Comment by plaisted** [comment]
Thanks @Tratcher, Are there any examples on this?

Since orders may be cached before the customer it seems like you'd have the create the `IChangeToken` and cache it separately. If a customer is cached it `GetsOrCreate`'s the `IChangeToken` and registers a post eviction callback on the customer Entry to fire the `IChangeToken` when the customer entry expires. When a order for a customer is cached it `GetsOrCreate`'s the `IChangeToken` and adds it as an expiration token for the entry. Is this the general idea of what you are suggesting?

**Comment by Tratcher** [comment]
The samples are being written for this new doc: https://github.com/aspnet/Docs/pull/4654

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
