### ISSUE TITLE
Add special case for WeakReferences

### ISSUE THREAD

**Issue by benaadams** [aspnet/Caching#191]
WeakReferences make be GC'd prior to expiry; if there target has been GC'd they should be removed from the cache

**Comment by muratg** [comment]
@sebastienros any risks you can see with this?

**Comment by Tratcher** [comment]
Something like this: a197fe6

**Comment by Tratcher** [comment]
Open question: since this does not require any changes to the MemoryCache, should we just add it as a sample instead?

**Comment by muratg** [comment]
@Tratcher let's decide the plan with this. We can move out if we're not doing this in 1.1.

**Comment by Tratcher** [comment]
@benaadams where do you want to use this? Is a sample sufficient?

**Comment by benaadams** [comment]
Want to use in response caching; a sample is probably fine and shows how flexible the cache can be. 

Can revisit if it becomes used in the actual framework.
