### ISSUE TITLE
add  Microsoft.Extensions.Caching.Redis to VS2015 issue. 

### ISSUE THREAD

**Issue by emailtowalter** [aspnet/Caching#192]
I got the following issue when I add Redis package to VS 2015. I am using RC2 .net core. 

 "Package Microsoft.Extensions.Caching.Redis 1.0.0-rc2-final is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.Caching.Redis 1.0.0-rc2-final supports: net451 (.NETFramework,Version=v4.5.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
"

**Comment by Tratcher** [comment]
Redis is not yet supported on Core: https://github.com/aspnet/Caching/pull/147
