### ISSUE TITLE
Redis cache strange behavior

### ISSUE THREAD

**Issue by dolly22** [aspnet/Caching#202]
I'm experiencing strange behavior of distributed redis cache when combined with Thread.Sleep (or another blocking workload). Simple repro case (ASP.NET Core RC2)

Startup.cs
```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...

    services.AddDistributedRedisCache(options =>
    {
        options.Configuration = "...";
    });
}
```

HomeController.cs
```csharp
public class HomeController : Controller
{
    public async Task<IActionResult> Index([FromServices]IDistributedCache cache)
    {
        var hitat = DateTime.UtcNow;
        var sw = new Stopwatch();
        sw.Start();
        
        var value = await cache.GetAsync("cache_key");
        sw.Stop();

        Thread.Sleep(20000);

        var rederedat = DateTime.UtcNow;
        return new ContentResult()
        {
            ContentType = "text/plain",
            Content = $"Hit at {hitat}, rendered {rederedat}, cache get duration {sw.ElapsedMilliseconds} ms"
        };
    }
}
```

I'm using Azure Redis Cache. When accessing this page multiple times in parallel, my results...

Hit at 7. 6. 2016 14:14:58, rendered 7. 6. 2016 14:15:18, cache get duration 510 ms
Hit at 7. 6. 2016 14:14:59, rendered 7. 6. 2016 14:15:38, cache get duration 19270 ms
Hit at 7. 6. 2016 14:15:00, rendered 7. 6. 2016 14:15:58, cache get duration 38757 ms
Hit at 7. 6. 2016 14:15:02, rendered 7. 6. 2016 14:16:18, cache get duration 56095 ms
Hit at 7. 6. 2016 14:15:04, rendered 7. 6. 2016 14:16:38, cache get duration 74689 ms

**Comment by Tratcher** [comment]
@kichalla can you repro this?

**Comment by kichalla** [comment]
Taking a look at it now.

**Comment by kichalla** [comment]
I am unable to repro it. I used a locally hosted redis server in my case.

@dolly22 are you able to repro it consistently?

**Comment by dolly22** [comment]
@kichalla I am able to reproduce on another computer, even with locally hosted redis server.

Local server...
Hit at 07.06.2016 19:26:11, rendered 07.06.2016 19:26:31, cache get duration 0 ms
Hit at 07.06.2016 19:26:12, rendered 07.06.2016 19:26:51, cache get duration 18608 ms
Hit at 07.06.2016 19:26:14, rendered 07.06.2016 19:27:11, cache get duration 37174 ms

I have uploaded test project to https://github.com/dolly22/aspnetcoreredistest, also deployed to azure web app - http://aspnetcoreredistest.azurewebsites.net/.

My steps to reproduce
1. Open three tabs in edge browser - http://aspnetcoreredistest.azurewebsites.net/
2. After all tabs finish loading, hit refresh for all tabs

**Comment by kichalla** [comment]
Thanks for the detailed repro.

We were able to isolate the issue to StackExchange's Redis client (ASP.NET's Caching uses this client behind the scenes). For example, in the following repro there is no ASP.NET Core component involved and checkout `Output.txt` file in the branch which shows the output that we see when running the repro.

https://github.com/kichalla/rediscacherepro/tree/stackexchangeredis/RedisRepro

**Comment by dolly22** [comment]
I think the problem is how StackExchange's Redis client is sychronously scheduling continuations 
[ResultBox.cs#L110](https://github.com/StackExchange/StackExchange.Redis/blob/29b5cc180ac560b61009ec68ea20ae1d2a0052d0/StackExchange.Redis/StackExchange/Redis/ResultBox.cs#L110) (http://blog.stephencleary.com/2012/12/dont-block-in-asynchronous-code.html) and also requires the completion thread to finish it's work [CompletionManager.cs#L124](https://github.com/StackExchange/StackExchange.Redis/blob/29b5cc180ac560b61009ec68ea20ae1d2a0052d0/StackExchange.Redis/StackExchange/Redis/CompletionManager.cs#L124) before allowing another threads to enter.

For now, I was able to workaround the issue in my case either by setting (NOT PROPERLY TESTED)

```csharp
ConnectionMultiplexer.PreserveAsyncOrder = false;
```
or inserting Task.Delay before synchronously blocking code
```csharp
await cache.GetAsync("cache_key");
await Task.Delay(1);  
```

**Comment by Tratcher** [comment]
OK, thanks for working that out. @dolly22 can you file a bug against stackexchange?
https://github.com/StackExchange/StackExchange.Redis/issues
