### ISSUE TITLE
The Microsoft.Extensions.Caching.Redis is not support netcoreapp1.0?

### ISSUE THREAD

**Issue by xbuilder** [aspnet/Caching#205]
When I import `Microsoft.Extensions.Caching.Redis` package from nuget,error occured:

`The dependency Microsoft.Extensions.Caching.Redis 1.0.0-rc2-final does not support framework .NETCoreApp,Version=v1.0.`

My "frameworks" config in `project.json` just like this:
```
"frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
```

**Comment by Tratcher** [comment]
Duplicate: https://github.com/aspnet/Caching/issues/121

**Comment by xbuilder** [comment]
So what should I do to solve this problem?
![image](https://cloud.githubusercontent.com/assets/10357081/15989090/ed25b5f4-309d-11e6-8e0f-b579ed954a81.png)

**Comment by davidfowl** [comment]
@xbuilder read the linked issue. It doesn't work on .NET Core yet and won't work until 1.0.1.
