### ISSUE TITLE
Redis is not supported for netstandard1.5 ? 

### ISSUE THREAD

**Issue by yzbai** [aspnet/Caching#208]
![default](https://cloud.githubusercontent.com/assets/2872145/16215070/388e3abc-3791-11e6-8215-ef866346248d.png)

**Comment by BrennanConroy** [comment]
Duplicate: #121

**Comment by yzbai** [comment]
When I create a new asp.net core web application on rc2,  just add ("Microsoft.Extensions.Caching.Redis": "1.0.0-rc2-final",) in project.json, the error appears.

It says, "The dependency Microsoft.Extensions.Caching.Redis 1.0.0-rc2-final does not support framework .NETCoreApp,Version=v1.0.	

Did I do something wrong?
