### ISSUE TITLE
SQLCache Set should allow a null timeout

### ISSUE THREAD

**Issue by iscifoni** [aspnet/Caching#209]
I have implemented sql cache:

```
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.SqlServer;

.
.
.

public void ConfigureServices(IServiceCollection services)
 {
      services.AddSingleton<IDistributedCache>(serviceProvider =>
      new SqlServerCache(
            new CacheOptions( new SqlServerCacheOptions()
            {
                  ConnectionString = @"Data Source=localhost;Initial Catalog=CacheDB;Integrated Security=False;User Id=sa;Password=pippo",
                  SchemaName = "dbo",
                  TableName = "testCache"
            })
      ));
 }

public void Configure(IApplicationBuilder app,  IDistributedCache cache)
{
      var serverStartTimeString = DateTime.Now.ToString();
      byte[] val = Encoding.UTF8.GetBytes(serverStartTimeString);
      cache.Set("lastServerStartTime", val);

      app.Run(async (context) =>
      {
            context.Response.ContentType = "text/html";
            await context.Response.WriteAsync("Hello World!");
      });
}


```
but when I execute the code, I receive the error "Either absolute or sliding expiration needs to be provided.".
This because at line 33 of [Microsoft.Extensions.Caching.Abstractions/DistributedCacheExtensions.cs](https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Abstractions/DistributedCacheExtensions.cs) the  DistributedCacheEntryOptions parameter is a new value, with no setting  for AbsoluteExpirationRelativeToNow or SlidingExpiration property.

If i use 
```

cache.Set("lastServerStartTime", val, new DistributedCacheEntryOptions()
{
      AbsoluteExpirationRelativeToNow = new TimeSpan(1,0,0)
});

```
All works fine.

Need to modify Microsoft.Extensions.Caching.Abstractions/DistributedCacheExtensions.cs  to pass default value forAbsoluteExpirationRelativeToNow or SlidingExpiration ??

**Comment by Tratcher** [comment]
The Redis and DistributedMemory cache implementations allows this, I wonder why the SQL one doesn't. @kichalla?

**Comment by kichalla** [comment]
@iscifoni Thanks for reporting this. This behavior is not ideal. For now you could probably create a new  extension on `IDistributedCache` which sets these options.

**Comment by kichalla** [comment]
I am thinking that SQL Server cache should have a default sliding expiration for a cache entry, let's say 20 mins, if none specified by a user. These default timeout options would be exposed by `SqlServerCacheOptions`.  

@iscifoni any thoughts on this?

**Comment by iscifoni** [comment]
For me the parameter DefaultSlidingExpiration on SqlServerCacheOptions class  is what we need :smile: .
