### ISSUE TITLE
GetOrCreate / GetOrCreateAsync on IMemoryCache creates cache entry even when factory throws

### ISSUE THREAD

**Issue by rmja** [aspnet/Caching#211]
It seems wrong that a cache entry is added with the value `null` when the factory method throws:

```
            try
            {
                memoryCache.GetOrCreate("key", entry =>
                {
                    throw new Exception();
                    return 123;
                });
            } catch (Exception e)
            {
                // memoryCache now has an entry for "key" with the value null. This seems odd.
            }
```

The expected behaviour should be that the value is not added to the cache if the factory throws.

**Comment by Tratcher** [comment]
Agreed. There should not be a using statement on this line: https://github.com/aspnet/Caching/blob/c432e5827e4505c05ac7ad8ef1e3bc6bf784520b/src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs#L103

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Caching/commit/18f22598da1d650dc0b3291254ed61df036a378f

**Comment by gdoron** [comment]
When will preview 1 be released?
We just got hit hard by this bug, we'll might have to use the nightly builds on production 😢 until it's being released.
