### ISSUE TITLE
GetOrCreateAsync likely causes multiple expensive calculations which could crash a server under load

### ISSUE THREAD

**Issue by ricklove** [aspnet/Caching#218]
# Recommended Pattern

I have been using MemoryCache to cache expensive calculations, using the recommended pattern:

- Try to get the value
- If it doesn't exist, create it and save it to cache

# Problem - Crash and Burn

However, there is a big problem for web servers under load:

- Assume Web Server is loaded and warmed up and all cache values are pre-populated
- Assume 1,000 requests / sec as average load
- Everything is fine
- Then Cache expires on an item that takes about 1 second to obtain or calculate (1MB cache object)
- The next request begins calculating the cache value which requires some async requests for other server resources.
- PROBLEM: The following 999 requests also begin trying to get the expensive value (because the cache value is still empty)
- The first request finally finishes and saves the 1MB cache object to cache
- BIG PROBLEM: The other 999 requests keep trying, until they start timing out
- Those that are successful replace the cache value and each one creates a 1MB chunk of garbage for the GC
- CRASH: The server becomes unresponsive and 50X errors abound. OutOfMemoryExceptions, CPU maxed out, etc.
- The server might recover after a while, but will probably try to reset itself.
- The server restarts and now the cache is cold, it has to populate all the cache items.
- As an added bonus, users are pilling up and hitting refresh like crazy and now there are 10,000 requests
- BURN: The server tries to populate the cache, now with 10,000 requests. (I don't know the number of max threads with asp.net core but that may be reached by now.)

# Solution?

GetOrCreateAsync should use a Timeout, so that only one request will try to create the value upon cache miss. 

Subsequent requests can use an old cache value if it exists. Otherwise, the subsequent requests should go into an await Task.Delay() loop up until the Timeout time and keep polling for the created value.

This will allow only one item to be created while the other requests will poll for the result without wasting massive amounts of resources.

# Code Example (Not Tested)

    public static class CacheExtensions
    {
        public static async Task<T> GetOrCreateAsync<T>(this IMemoryCache memoryCache, string key, Func<MemoryCacheEntryOptions> createOptionsCallback, Func<Task<T>> createCallback)
        {
            var maxRefreshTime = TimeSpan.FromSeconds(60);
            var longTermExtraTime = TimeSpan.FromSeconds(120);
            var refreshKey = "___" + key + "___RefreshStartTime";
            var longTermKey = "___" + key + "___LongTerm";

            T value;
            DateTime refreshStartTime;

            // Try to get value in cache 
            if (!memoryCache.TryGetValue(key, out value))
            {
                // If expired or first request

                // Check if being refreshed already
                if (!memoryCache.TryGetValue(refreshKey, out refreshStartTime) || DateTime.UtcNow > refreshStartTime + maxRefreshTime)
                {
                    // If is not already being refreshed
                    memoryCache.Set(refreshKey, DateTime.UtcNow);

                    value = await createCallback();

                    var options = createOptionsCallback();
                    memoryCache.Set(key, value, options);

                    var longOptions = createOptionsCallback();
                    if (longOptions.AbsoluteExpiration.HasValue) { longOptions.AbsoluteExpiration += longTermExtraTime; }
                    if (longOptions.SlidingExpiration.HasValue) { longOptions.SlidingExpiration += longTermExtraTime; }
                    memoryCache.Set(longTermKey, value, longOptions);
                }

                // Try to use the long term value
                if (!memoryCache.TryGetValue(longTermKey, out value))
                {
                    // If no long value, wait and try again (up to 60 seconds)
                    for (int i = 0; i < 60; i++)
                    {
                        await Task.Delay(1000);
                        if (memoryCache.TryGetValue(key, out value))
                        {
                            return value;
                        }
                    }

                    throw new TimeoutException("Failed to Acquire Value");
                }

            }

            return value;
        }
    }

**Comment by muratg** [comment]
This is hypothetical at this point. Also, any fix is a breaking change that we can'd make in 1.x.
