### ISSUE TITLE
Memory Cache file system dependency example

### ISSUE THREAD

**Issue by pholly** [aspnet/Caching#231]
The asp.net docs state:

> You can configure cache entries to depend on other cache entries, the file system, or programmatic tokens, evicting the entry in response to changes.

I assume cache entries can depend on file system changes by using `ChangeToken`s. I searched and found that `Microsoft.Extensions.FileProviders.Physical.FileSystemProvider` has a `Watch` function that returns an `IChangeToken`. Is that what we're supposed to use? Can someone provide an example on how to make a cache entry depend on a file on the filesystem?

**Comment by mikaelm12** [comment]
> I assume cache entries can depend on file system changes by using ChangeTokens. I searched and found that Microsoft.Extensions.FileProviders.Physical.FileSystemProvider has a Watch function that returns an IChangeToken. 

Hey @pholly. You're right. You want to use the `IChangeToken` returned from calling `Watch` on the file of interest. 

There is a new sample here that shows you how to do it
https://github.com/aspnet/Caching/tree/dev/samples/MemoryCacheFileWatchSample 

Hope this helps!
