### ISSUE TITLE
the in memory cache default options dont influence

### ISSUE THREAD

**Issue by yosigolan** [aspnet/Caching#233]
When configuring in memory cache in the startup class like this:
services.AddMemoryCache()

there is an option to add setupAction like this:

```
 services.AddMemoryCache(options => new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromMinutes(1)).RegisterPostEvictionCallback(
                        (key, value, reason, substate) =>
                        {
                            Console.WriteLine($"'Cache item {key}' was evicted because: {reason}");
                        }
                        ));
```

how ever it does not influence the cache behavior. the call back is not called and the item is not evicted on time. only when using the same options when setting some item into the cache the options influence the behavior.

**Comment by Tratcher** [comment]
That's not how that works. AddMemoryCache takes an `Action<MemoryCacheOptions>`. MemoryCacheEntryOptions must be set per entry, there are no global settings.

**Comment by yosigolan** [comment]
Thanks for that clarification. from syntax point of view, why is it possible to pass any object on that action and not only MemoryCacheOptions?

Thanks Yosi

**Comment by Tratcher** [comment]
Here's what the compiler sees. Actions do not have a return parameter or statement, they're void. The MemoryCacheEntryOptions is created and discarded.

```
private static IApplicationBuilder AddMemoryCache(this IApplicationBuilder builder, Action<MemoryCacheOptions> configureOptions) { ... };

private void AnonymousMethod1(MemoryCacheOptions options)
{
   new MemoryCacheEntryOptions()
     .SetAbsoluteExpiration(TimeSpan.FromMinutes(1))
     .RegisterPostEvictionCallback((key, value, reason, substate) =>
     {
       Console.WriteLine($"'Cache item {key}' was evicted because: {reason}");
     });
}

services.AddMemoryCache(new Action<MemoryCacheOptions>(AnonymousMethod1));
```

Your code would only make sense if AddMemoryCache took a `Func<MemoryCacheOptions, MemoryCacheEntryOptions>`, Funcs have return parameters. Then you'd get:

```
private MemoryCacheEntryOptions AnonymousMethod2(MemoryCacheOptions options)
{
   return new MemoryCacheEntryOptions()
     .SetAbsoluteExpiration(TimeSpan.FromMinutes(1))
     .RegisterPostEvictionCallback((key, value, reason, substate) =>
     {
       Console.WriteLine($"'Cache item {key}' was evicted because: {reason}");
     });
}
```

**Comment by yosigolan** [comment]
Thanks.
fully understood now.

Yosi
