### ISSUE TITLE
Unable to resolve 'Microsoft.Web.Redis.RedisSessionStateProvider (>= 2.0.238)' for '.NETCoreApp,Version=v1.0'.

### ISSUE THREAD

**Issue by goupadhy** [aspnet/Caching#235]
Hi, 

I'm trying to use redis as session state provider for an asp.net 5 core application in using VS Code in Linux. When i try to restore this package it fails and shows "Unable to resolve 'Microsoft.Web.Redis.RedisSessionStateProvider (>= 2.0.238)' for '.NETCoreApp,Version=v1.0'."
Can you please suggest what needs to be done?

**Comment by Tratcher** [comment]
That's for Asp.Net 4.0, not Asp.Net Core. I think you're looking for Microsoft.Extensions.Caching.Redis, but you'll need 1.1.0 from the nightly feed for .Net Core support.

**Comment by goupadhy** [comment]
Hi Tratcher, Thanks for your response. Yes i'm looking for  Package Microsoft.Extensions.Caching.Redis but the current 1.0.0-rc2-fina  is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Can you tell me how I can get 1.1.0?

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Home/wiki/NuGet-feeds, you need the aspnetcore-dev feed.

**Comment by goupadhy** [comment]
Thanks a lot Chris. One more question do you know if we can use redis cache in Asp.Net core for Linux as session state provider? Any sample or post would be of great help!

**Comment by Tratcher** [comment]
Yes: https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L36

**Comment by goupadhy** [comment]
This sample is for in memory/sql server as session provider. The redis implementation piece is missing in it. Do you have any sample for redis implementation Asp.Net core for Linux as session state provider?

**Comment by Tratcher** [comment]
Session depends on IDistributedCache, and RedisCache implements IDistributedCache. All you have to do is register it `services.AddSingleton<IDistributedCache, RedisCache>();` and set the options: https://github.com/aspnet/Caching/blob/dev/samples/RedisCacheSample/Program.cs#L32

**Comment by goupadhy** [comment]
The code looks like this.

#if NET451
            // Uncomment the following line to use the Redis implementation of IDistributedCache.
            // This will override any previously registered IDistributedCache service.
            services.AddSingleton<IDistributedCache,Redis >();
#endif

It has a if clause which says if NET451 then use redis. My guess is we are checking if .Net framework 4.5 then it targets redis. I want to use redis in Asp.Net 5 core then i'm in trouble as when i use 

using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Redis;

var cache = new RedisCache(new RedisCacheOptions  // has error
            {
                Configuration = "localhost",
                InstanceName = "SampleInstance"
            });
when i do a package restore i get this error
Unable to resolve 'Microsoft.Extensions.Caching.Redis "(>= 1.1.0)' for '.NETCoreApp,Version=v1.0'.
ERROR: Error: Command failed: dotnet restore "/Users/goupadhy/MyNewAspSessionApp/project.json"

Can you please tell me what i'm doing wrong here?

**Comment by Tratcher** [comment]
The #if NET451 is no longer needed, it was there because RedisCache formerly only supported .Net 4.5.1.

Did you add the myget feed referenced above?
Is the project.json dependency specified as `"Microsoft.Extensions.Caching.Redis": "1.1.0-*"`?

**Comment by goupadhy** [comment]
Yes i have referenced  "Microsoft.Extensions.Caching.Redis": "1.1.0-*" in package.json. I'm new to Asp.Net core Stupid question but How to add myget feed referenced?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Caching/blob/dev/NuGet.config#L4, but use aspnetcore-dev

**Comment by goupadhy** [comment]
Thanks a lot Chris for helping me all along :) getting error in services.addsession()  app.UseSession();  section i;m referencing "Microsoft.AspNetCore.Session": "1.0.0-rc2-final" 

public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IDistributedCache, RedisCache>();
    services.AddSession(); //getting error 

//-----------

public void Configure(IApplicationBuilder app)
{
   app.UseSession();  //I'm getting error ApplicationBuilder' does not contain a definition for 'useSession' and no extension method 'useSession' accepting a first argument of type 'IApplicationBuilder'
}

**Comment by goupadhy** [comment]
I have added below code in my asp.net net core app
 public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
          services.AddMvc();        
          services.AddDistributedMemoryCache();
	 services.AddSession();  

I’m referring  this "Microsoft.Extensions.Caching.Redis": "1.1.0-*" ,
     "Microsoft.AspNetCore.Session": "1.0.0-rc2-final"

pointing to 
  <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />

//getiting an error for this when i run the app
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.SessionServiceCollectionExtensions.AddSession(IServiceCollection services)
   at Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Startup.Main(String[] args)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
