### ISSUE TITLE
How do I make one cache entry expire when another one changes?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Caching#236]
I'm looking for the equivalent to `System.Runtime.Caching`'s `MemoryCache.CreateCacheEntryChangeMonitor` - Basically, expire one cache key if a different one is modified. The documentation says this is possible ("You can configure cache entries to depend on other cache entries") but doesn't explain how to actually do it.

I created a doc task too: https://github.com/aspnet/Docs/issues/1938

**Comment by Tratcher** [comment]
You can't directly link two entries, but entries can be removed based on IChangeTokens and you can use the same token for multiple entries.
https://github.com/aspnet/Caching/blob/dev/samples/MemoryCacheSample/Program.cs#L84-L96

Change tokens can even be inherited automatically:
https://github.com/aspnet/Caching/blob/dev/samples/MemoryCacheSample/Program.cs#L98-L114

**Comment by Daniel15** [comment]
So I need to maintain the cancellation tokens myself? If I have a web app with lots of stuff being cached, I'd need to have my own map of cancellation tokens too? That seems like boilerplate that should be unnecessary given `System.Web.Caching.Cache` and  `System.Runtime.Caching` both allow dependencies on other cache entries without needing to manually mess with tokens yourself.

It sounds like the documentation is incorrect in its assertion that you can configure cache entries to depend on other cache entries.

**Comment by Tratcher** [comment]
How do you update the the first entry?

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
