### ISSUE TITLE
All Unit Tests (xUnit) are returning -2147450749 code and no visible Tests showing up in Visual Studio Test Explorer Window

### ISSUE THREAD

**Issue by fletchsod-developer** [aspnet/Caching#243]
Using the latest version of source code from this GitHub repository (Dated: 10/26/2018) & following step to reproduce this bug report.

The returned negative number -2147450749 is the error code coming from .NET CLI.

1) Open solution into VS-2015
2) Build (or rebuilt) solution
3) Error message below from the Output window & no visible tests showing up in Test Explorer (VS-2105).

------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.1676838) ==========
------ Discover test started ------
Discovering tests in 'X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.Memory.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.Memory.Tests\project.json" --output "X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.Memory.Tests\bin\Debug\netcoreapp1.1" --port 37084 --parentProcessId 43680 --no-build]
'test-xunit' returned '-2147450749'.
Discovering tests in 'X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.Redis.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.Redis.Tests\project.json" --output "X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.Redis.Tests\bin\Debug\netcoreapp1.1" --port 37088 --parentProcessId 43680 --no-build]
'test-xunit' returned '-2147450749'.
Discovering tests in 'X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.SqlServer.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.SqlServer.Tests\project.json" --output "X:\Playground\Caching-dev\test\Microsoft.Extensions.Caching.SqlServer.Tests\bin\Debug\netcoreapp1.1" --port 37093 --parentProcessId 43680 --no-build]
'test-xunit' returned '-2147450749'.
========== Discover test finished: 0 found (0:00:01.0875744) ==========

Windows 10
Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

**Comment by Tratcher** [comment]
They probobly require a later version of the CLI than you have installed.
https://github.com/dotnet/core/blob/master/release-notes/preview-download.md

Alternatively, try running build.cmd from the command line. It pulls the needed dependencies to a user dir (which won't fix VS, but at least you can run the tests one way).

**Comment by fletchsod-developer** [comment]
Interesting.  I ran this build.cmd command line and it works fine.   No changes in VS as you said.  Would have be nice to do the step-into & step-over debugger in visual studio.  :-/

**Comment by Tratcher** [comment]
Yeah, build.cmd manages it's own dependencies. It installs a pre-release SDK to `C:\Users\myuser\AppData\Local\Microsoft\dotnet\` and adds it to your PATH. You can have VS pick this one up by going to your system environment variables and remove the primary SDK from your PATH: `C:\Program Files\dotnet`. Restart VS and then the tests should work again.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
