### ISSUE TITLE
TryGetValue causes exception inside try-catch block when key not in cache

### ISSUE THREAD

**Issue by jwdavidson** [aspnet/Caching#244]
I wanted to add MemoryCache to some existing code where the existing code had a try/catch block ending with this sample:

        [HttpGet("api/actionsignifiers")]
        public IActionResult GetActionSignifiers() {
            try {
                List<SelectListItem> cachedActionSignifiers = new List<SelectListItem>();
                if (!_memoryCache.TryGetValue(ACTIONKEY, out cachedActionSignifiers)) {
                    List<SelectListItem> journalPageAll = _journalSvc.GetActionSignifiers();
                    if (journalPageAll == null) {
                        return new NotFoundResult();
                    }
                    _memoryCache.Set(ACTIONKEY, journalPageAll, _cacheOpts);
                    return new OkObjectResult(journalPageAll);
                }
                return new OkObjectResult(cachedActionSignifiers);
            }
            catch (Exception ex) {
                Log.Error(ex, "API - JournalPage::GetActionSignifiers()");
                return new BadRequestResult();
            }
        }
The problem here is that it becomes impossible to initialize the cache as the TryGetValue test causes a NullReferenceException. The NullReferenceException does not occur if the TryGetValue is not in a try/catch block.

**Comment by davidfowl** [comment]
Can you show the exception callstack? Also, do you have an isolated repro?

**Comment by jwdavidson** [comment]
Ignore my last. The NullReferenceException was for an uninitialized cache not the key. 

I hate that thisw exception never tells you what the NullReference is.
