### ISSUE TITLE
CancellationToken support

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Caching#245]
Why there is no cancellation token param in GetAsync or GetStringAsync?

In my project, I need this feature. I want to stop getting cache result in some scene.

**Comment by Tratcher** [comment]
On the IDistributedCache I assume?

Is the cache taking too long? What implementation are you using?

**Comment by Kagamine** [comment]
Yep. It didn't take too long, but I'm using that in Task.WaitAny(). I want to stop the others while any Task finished.
