### ISSUE TITLE
AddExpirationToken extension is not thread safe

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Caching#247]
I've noticed that `CacheEntryScopeExpirationTests.LinkContexts_AreThreadSafe` test can occasionally fail when run repeatedly at https://github.com/aspnet/Caching/blob/dev/test/Microsoft.Extensions.Caching.Memory.Tests/CacheEntryScopeExpirationTests.cs#L475. 

I will usually see one or two failures when repeating this test 50 times. I have reproduced this on Win10 x64 and Win10 x86.

cc @Tratcher

**Comment by JunTaoLuo** [comment]
Looks like the `AddExpirationToken` (https://github.com/aspnet/Caching/blob/efbbdc5e0a8c8a664ea34cd41220d084b6906f57/src/Microsoft.Extensions.Caching.Abstractions/CacheEntryExtensions.cs#L29-L40) is not thread safe.

The issue arises when `AddExpirationToken` is called from different threads concurrently. Since they operate on the underlying `ExpirationTokens`, an `IList`, is not thread safe, some tokens may not be added.

I see a few ways around this:

1. Use `ICollection.SyncRoot` of the `ExpirationTokens` collection for synchronization.
2. There's already a lock object for each entry we can use for synchronization though it's not exposed. We can move this extension to the interface instead.
3. Make`ExpirationTokens` a thread safe collection

**Comment by Tratcher** [comment]
If there's going to be a lock it should be here: https://github.com/aspnet/Caching/blob/21c850aad3a7338bfa400e146433ad3b2d9d441a/src/Microsoft.Extensions.Caching.Memory/CacheEntry.cs#L325
