### ISSUE TITLE
Concurrent connection on redis cache leads to connection leak

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Caching#257]
Need to port fix in https://github.com/aspnet/Caching/commit/3522082828cd0c411f297d50db289518f7844dee to 1.0.4 branch when available.

**Comment by muratg** [comment]
(Setting milestone to 1.0.2 to reflect the actual package version to be shipped.)

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Eilon** [comment]
@muratg please assign this bug.

**Comment by JunTaoLuo** [comment]
Patch merged. Leaving the issue open since version numbers will need to be updated.

**Comment by JunTaoLuo** [comment]
Version numbers updated
