### ISSUE TITLE
MemoryCache Compact may not remove any cache items

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Caching#263]
Not sure if this is by design but the behaviour outlined in https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L293 is not accurate.

Compact removes expired items, then removes items by priority. However, pinned items with priority of `NeverRemove` will, as the enum suggest, never be removed. If a cache needs to be compacted and consists of solely unexpired pinned cache entries then no compaction will occur, hence the percentage of items to remove will not be met. If the original purpose is to reduce memory usage, then Compact no-oping is somewhat unexpected. At the minimum we should update the comment to say that Compact only tries to remove entries that does not have the priority `NeverRemove`.

**Comment by Tratcher** [comment]
Yes, this is the intended behavior.

**Comment by JunTaoLuo** [comment]
Will update the comments in #221
