### ISSUE TITLE
CacheExtensions.GetOrCreateAsync() deadlock because configureAwait(false) is not specified

### ISSUE THREAD

**Issue by davidsleep** [aspnet/Caching#264]
### Functional impact
If I call the GetOrCreateAsync method and use .result to store the returned values the code goes into deadlock.

### Minimal repro steps
1.  Create a windows form project

2.  Add a button

3.  Add the following code

```
        private void button1_Click(object sender, EventArgs e)
        {
            MemoryCache cache = new MemoryCache(new MemoryCacheOptions());

            Func<ICacheEntry, Task<int>>  factory  = async cacheEntry =>
            {
                return await DoWorkAsyncInternal();
            };

            var list = cache.GetOrCreateAsync(100, factory).Result;
        }

        private async Task<int> DoWorkAsyncInternal()
        {
            Console.WriteLine("Inside DoWorkAsync");
            await Task.Delay(1000);
            return 42;
        } 
```
4.  Once you click the button the code will go into deadlock

### Expected result
The code should continue running as normal. 

### Actual result
The code goes into deadlock

NOTE:
I took a local copy of the CacheExtensions class and added configureAwait(false) to the await call.  This fixed the issue.

**Comment by benaadams** [comment]
Out of curiosity, what happens if you change it to:
```csharp
var list = cache.GetOrCreateAsync(100, factory).ConfigureAwait(false).GetAwaiter().GetResult();
```

**Comment by JunTaoLuo** [comment]
This is deadlocking because you are blocking on the result of an async function. Is it possible for you to make `button1_Click` async and `await cache.GetOrCreateAsync(...);`?

**Comment by davidsleep** [comment]
@benaadams Hey I added this code with no luck.  Still have async issues.

@JunTaoLuo So with the solution I am working on, the calling method of cache.GetOrCreateAsync() has to be sync and cannot be made async.

**Comment by benaadams** [comment]
And if you add it to your factory?
```csharp
private async Task<int> DoWorkAsyncInternal()
{
    Console.WriteLine("Inside DoWorkAsync");
    await Task.Delay(1000).ConfigureAwait(false);
    return 42;
} 
```

**Comment by JunTaoLuo** [comment]
Is it possible to use the blocking extension `GetOrCreate()` instead of `GetOrCreateAsync()` in your code?

**Comment by davidsleep** [comment]
@benaadams Hey, I added this code and still get the same issue.

@JunTaoLuo This does work but we have both async and sync methods we would like to use this code for.  Preferably we would like to call the same method to avoid duplicating code.

**Comment by Shane88** [comment]
Hi @JunTaoLuo and @benaadams, I'm helping @davidsleep write some code when we ran into this issue. We understand why this problem is occurring, we were raising this issue to identify what we believe is code that should be fixed in this library. 

https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs#L117

Copied here for convenience 

```cs
public static async Task<TItem> GetOrCreateAsync<TItem>(this IMemoryCache cache, object key, Func<ICacheEntry, Task<TItem>> factory)
{
   object result;
   if (!cache.TryGetValue(key, out result))
   {
       var entry = cache.CreateEntry(key);
       result = await factory(entry); // <-- This should use ConfigureAwait(false)
       entry.SetValue(result);
       // need to manually call dispose instead of having a using
       // in case the factory passed in throws, in which case we
       // do not want to add the entry to the cache
       entry.Dispose();
   }

   return (TItem)result;
}
```

According to Async/Await Best Practices we should always use ConfigureAwait(false) unless the we are relying on the SynchronizationContext, or have some sort of thread affinity. https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

Regardless of the issue we are facing, I believe this is something that this library should do anyway. 

Can ConfigureAwait(false) be added to the line of code mentioned?

**Comment by Tratcher** [comment]
The ASP.NET Core project does not have consistent guidelines or usage regarding ConfigureAwait. We have thousands of lines where this may be applicable. Let's try to avoid changing them one at a time. @Eilon.

That said, I think we are dependent on the context flow in this instance, we use it to flow expiration tokens from nested cache lookups. @JunTaoLuo can you verify that?

**Comment by JunTaoLuo** [comment]
@Tratcher Are you referring to `CacheEntryHelper` https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/CacheEntryHelper.cs#L17-L46? 

We depend on the `ExecutionContext` here with references to `CallContext` and `AsyncLocal` but not `SynchronizationContext` so it should be safe to add `.ConfigureAwait(false)` to our `GetOrCreateAsync()` without affecting the way we resolve "current/parent" cache entries. That said, I believe the APIs `GetOrCreateAsync()` and `GetOrCreate()`were designed to be used separately for async calls and non-async calls, respectively, and we don't recommend blocking on the async API. This is why I suggested using async and non-async versions separately depending on how it's called. I agree that if we want to support blocking on async APIs will need to change that across the board and should ask @Eilon about it.

In the mean time, I'll do a scan through the rest of the code base to see if there are any other parts that depends on context flow.

**Comment by benaadams** [comment]
```csharp
var list = Task.Run(() => cache.GetOrCreateAsync(100, factory)).ConfigureAwait(false).Result;
```
:trollface: 

Seriously though, calling `.Result` on an non-completed task is asking for trouble...

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
