### ISSUE TITLE
Remove cached object when user change origin/source of it, so cached object is obsolete.

### ISSUE THREAD

**Issue by emelhu** [aspnet/Caching#275]
I had made a realization of idea I had written at https://github.com/aspnet/Caching/issues/187

You can see it at https://github.com/emelhu/MemoryCache_DropOutToken

If you appreciate these i should make a new branch of https://github.com/aspnet/Caching and push it.

**Comment by Tratcher** [comment]
How is this different from using the existing ChangeToken infrastructure?
https://github.com/aspnet/Caching/blob/dev/samples/MemoryCacheSample/Program.cs#L84-L96

**Comment by emelhu** [comment]
"How is this different..."

It's simpler? :)

You're right, it's a similar solutions but i didn't knew it (I saw, but I was not listening enough)... so now i "invented hot water" :)

**Comment by emelhu** [comment]
I enclose the test program (for everyone who is interested):

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// https://github.com/aspnet/Caching/issues/275

namespace MemoryCacheTestApp
{
  using System.Threading;
  using Microsoft.Extensions.Caching.Memory;
  using Microsoft.Extensions.Primitives;
  using System.Diagnostics;

  class Program
  {
    private static IMemoryCache memoryCache;

    private static CancellationTokenSource token1 = new CancellationTokenSource();
    private static CancellationTokenSource token2 = new CancellationTokenSource();

    private static Stopwatch    stopwatch;

    static void Main(string[] args)
    {
      Console.WriteLine();
      Console.BackgroundColor = ConsoleColor.DarkBlue;
      Console.ForegroundColor = ConsoleColor.Yellow;
      Console.WriteLine(" * Microsoft.Extensions.Caching.MemoryCache / CancellationChangeToken test. * ");
      Console.WriteLine();
      Console.WriteLine();
      Console.ResetColor();

      var testItems = GetTestList();

      var memoryCacheOptions = new MemoryCacheOptions();
      memoryCacheOptions.ExpirationScanFrequency = TimeSpan.FromMilliseconds(500);

      memoryCache   = new MemoryCache(new MemoryCacheOptions());

      var cts = new CancellationTokenSource(10 * 1000);

      var task = Task.Run(() =>
            {
              while (!cts.IsCancellationRequested)
              {
                memoryCache.Set<string>(Guid.NewGuid(), String.Concat(Enumerable.Repeat(Guid.NewGuid().ToString(), 100))); 
                Thread.Sleep(10);
              }
            });

      stopwatch = Stopwatch.StartNew();

      StoreCacheItems(testItems);

      for (int times = 0; times < 10; times++)
      {
        if ((stopwatch.ElapsedMilliseconds > 5000) && !token1.IsCancellationRequested)
        {
          token1.Cancel();
          Console.WriteLine("token1.Cancel()");
          Console.WriteLine();
        }

        if ((stopwatch.ElapsedMilliseconds > 7000) && !token2.IsCancellationRequested)
        {
          token2.Cancel();
          Console.WriteLine("token2.Cancel()");
          Console.WriteLine();
        }

        PrintCacheItems(testItems);

        Thread.Sleep(1000);
      }

      cts.Cancel();

      task.Wait();

      Console.WriteLine();
      Console.Write("Press Enter to exit...");
      Console.ReadLine();
    }

    
    public static List<CacheTestItem> GetTestList()
    {
      var list = new List<CacheTestItem>();

      list.Add(new CacheTestItem("TEST_D2000",         2000));
      list.Add(new CacheTestItem("TEST_D4000",         4000));
      list.Add(new CacheTestItem("TEST_D4000_Token1",  4000, token1));
      list.Add(new CacheTestItem("TEST_D6000_Token1",  6000, token1));
      list.Add(new CacheTestItem("TEST_D6000_Token2",  6000, token2));
      list.Add(new CacheTestItem("TEST_D8000_Token2",  8000, token2));

      return list;
    }

    public static void StoreCacheItems(List<CacheTestItem> testItems)
    {
      foreach (var item in testItems)
      {
        var options = new MemoryCacheEntryOptions();

        options.AbsoluteExpirationRelativeToNow = item.delay;

        if (item.token != null)
        {
          options.AddExpirationToken(new CancellationChangeToken(item.token.Token));

        }

        memoryCache.Set<string>(item.key, item.data, options);    // Set<TItem>(this IMemoryCache cache, object key, TItem value, MemoryCacheEntryOptions options)
      }      
    }

    private static void PrintCacheItems(List<CacheTestItem> testItems)
    {
      Console.WriteLine("Elapsed milliseconds: " + stopwatch.ElapsedMilliseconds.ToString());

      foreach (var item in testItems)
      {
        Console.WriteLine("{0,-17}: {1}", item.key, memoryCache.Get<string>(item.key));
      }   
      
      Console.WriteLine(); 
    }

  }

  public struct CacheTestItem
  {
    public string                   key;
    public string                   data;
    public TimeSpan                 delay;
    public CancellationTokenSource  token;

    public CacheTestItem(string key, int delayMilliSec, CancellationTokenSource token = null)
    {
      this.key    = key;
      this.data   = "Test data:" + Guid.NewGuid().ToString() + " [" + key + "]";
      this.delay  = TimeSpan.FromMilliseconds(delayMilliSec);
      this.token  = token;
    } 
  }
}
