### ISSUE TITLE
Redis DistributedCache allow specify Database number

### ISSUE THREAD

**Issue by msmolka** [aspnet/Caching#276]
Currently there is no way to specify Database Number in Redis Cache system

**Comment by sebastienros** [comment]
This can be set in the connection string, see here: https://github.com/ServiceStack/ServiceStack.Redis#redis-connection-strings

For instance, `redis://clientid:password@localhost:6380?ssl=true&db=1` will use database `1`

**Comment by MichaCo** [comment]
@sebastienros ServiceStack is the wrong client I think ;)
That being said, StackExchange.Redis also supports setting the database via connection string
https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md#configuration-options => `defaultDatabase`

/cc @msmolka

**Comment by sebastienros** [comment]
Oops, thanks!

**Comment by msmolka** [comment]
@MichaCo my bad. I noticed only GetDatabse with number but missed connection option.

**Comment by JunTaoLuo** [comment]
Seems like this was resolved
