### ISSUE TITLE
Add baselines to enable checks for breaking changes

### ISSUE THREAD

**Issue by dougbu** [aspnet/Caching#287]
One shipped project in this repo lacks baselines. Looks like baseline files (`baseline.net45.json` and `baseline.netcore.json`) should be created in `release` or `rel/1.0.1` and checked into at least `dev`. The details below are reformatted from a recent Universe build on the CI.
```
[Caching\src\Microsoft.Extensions.Caching.Redis\Microsoft.Extensions.Caching.Redis.csproj]
  No baseline file for netstandard1.5 found in Microsoft.Extensions.Caching.Redis.
```

**Comment by JunTaoLuo** [comment]
I added that as part of https://github.com/aspnet/Caching/pull/288
