### ISSUE TITLE
Small perf wins inside MemoryCache

### ISSUE THREAD

**Issue by ilmax** [aspnet/Caching#29]
Hi, I was looking at the caching code and I found some points which can be enhanced to avoid creating unnecessary objects. I'm referring to the class [MemoryCache](https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Cache.Memory/MemoryCache.cs), the private field _entries can be a `Dictionary<string, CacheEntry>` instead of an` IDictionary<string, CacheEntry>` (since it's private and it's always initialized to a `Dictionary<string, CacheEntry>`) thus saving some unnecessary memory allocation when iterating over Keys and Values. Also the `RemoveEntries` method could be changed to accept a `List` instead of `IEnumerable<CacheEntry>` (since it's a private method always called with an instance of `List<CacheEntry>`) saving 1 object allocation when iterating over the list of entries. This change will also be consistent with the method `ExpirePriorityBucket` which already accept generic lists parameters.

It's not a huge improvement, but it's a fairly simple one at least IMHO.

Max.

**Comment by justinvp** [comment]
FYI, I noticed these as well and went ahead and fixed them while making some other changes in #74.

**Comment by justinvp** [comment]
Fixed by #74. This can be closed.
