### ISSUE TITLE
Discussion: Removal of MemoryCache's GC compaction trigger 

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Caching#290]
Discussion for https://github.com/aspnet/Announcements/issues/228

**Comment by Antaris** [comment]
Question - why the requirement to downcast, instead of defining the `Compact` method on `IMemoryCache`?

**Comment by JunTaoLuo** [comment]
We did try this in a previous iteration when removing the compaction trigger. However, this functionality is specific to our implementation in `MemoryCache` and it's unclear whether we should require every `IMemoryCache` to support `Compact`. cc @davidfowl @Tratcher ?

**Comment by Tratcher** [comment]
The Compaction needs a better design before it's exposed on the interface.

**Comment by JunTaoLuo** [comment]
It's unlikely that `Compact` will remain once we revisit the design of `MemoryCache` in #289.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
