### ISSUE TITLE
Microsoft.Extensions.Caching.Abstractions should target full .NET Framework

### ISSUE THREAD

**Issue by shaynevanasperen** [aspnet/Caching#291]
I want to publish a NuGet package that targets `netstandard1.1`, `netstandard1.3`, `net45` and `net46`. My package depends on [Microsoft.Extensions.Caching.Abstractions](http://www.nuget.org/packages/Microsoft.Extensions.Caching.Abstractions/) but since that package only targets `netstandard1.0`, I can't support `net45` or `net46` without requiring consumers stuck on those older frameworks having to install the whole contents of the [NetStandard.Library 1.6.1 meta-package](http://www.nuget.org/packages/NETStandard.Library/).

This actually highlights a much wider issue: In theory, libraries targeting `NetStandard` are supposed to be natively supported by the full .NET Framework. But in practice, if they don't also target older TFMs then consuming projects built against the full .NET Framework have to install a load of NuGet packages: 

![image](https://cloud.githubusercontent.com/assets/1126129/24522868/e110627a-1588-11e7-9f86-78dc7a57ac65.png)

Which of the above libraries is **actually** required by [Microsoft.Extensions.Caching.Abstractions](http://www.nuget.org/packages/Microsoft.Extensions.Caching.Abstractions/)? I bet maybe one or two only! It should depend on only the smallest set of dependencies it needs, rather than the whole  [NetStandard.Library 1.6.1 meta-package](http://www.nuget.org/packages/NETStandard.Library/)!

As a NuGet package author, I shouldn't have to target older TFMs such as `net45` and `net46`, but unfortunately I _do_ have to in order to not scare the living crap out of anyone who wants to install my package in a project that has not yet, or will never be, upgraded to .NET Core.

I even tried adding this to my consuming .NET Framework project, but unfortunately it doesn't work:

```xml
<PropertyGroup>
  <PackageTargetFallback>$(PackageTargetFallback);netstandard1.0;</PackageTargetFallback>
</PropertyGroup>
```

NetStandard was supposed to be great. It's a shame Microsoft messed it up so badly. In the meantime, until it get's fixed at the platform level, please make the [Microsoft.Extensions.Caching.Abstractions](http://www.nuget.org/packages/Microsoft.Extensions.Caching.Abstractions/) library target older TFMs.

**Comment by natemcmaster** [comment]
It seems there are a few separate concerns here, but I'll simplify this to (1) too many packages and (2) .NET Framework 4.5 support.

As we announced last week, we intend to move this and all Microsoft.Extensions.\* packages to .NET Standard 2.0 before the 2.0.0 release (see https://github.com/aspnet/Announcements/issues/249). This will address **(1)** as NETStandard.Library 2.0.0 will consolidate the dozens of System.\* packages down to two. However, this will not address **(2)** as a part of this. .NET Standard 2.0 requires .NET Framework 4.6.1.

Closing as this is not something we indent to change at the moment. If you have more feedback, https://github.com/aspnet/Home/issues/2045 is the best place to discuss this move.
