### ISSUE TITLE
Redis exception on linux

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Caching#292]
using the  on windows/windows nano docker works great, the same code targeting docker linux however throws exception on trying the get values from the redis server ?

An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code occurred.

Stack Trace:
"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)\n   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)\n   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)\n   at Microsoft.Extensions.Caching.Redis.RedisCache.Connect()\n   at Microsoft.Extensions.Caching.Redis.RedisCache.GetAndRefresh(String key, Boolean getData)\n   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetString(IDistributedCache cache, String key)\n   at MorrisonDataServices.AspNetCore.WebApplication.Controllers.HomeController.Index() in C:\\DEV\\MDS\\MorrisonDataServices.AspNetCore\\src\\MorrisonDataServices.AspNetCore.WebApplication\\Controllers\\HomeController.cs:line 29"

**Comment by Tratcher** [comment]
This does not appear to be ASP.NET related. It's either StackExchange.Redis (https://github.com/StackExchange/StackExchange.Redis) or .Net Core.

**Comment by grahamehorner** [comment]
@thatcher I will link StackExchange.Redis to this issue

**Comment by grahamehorner** [comment]
Is it worth considering implementing some integration tests so should StackExchange.Redis implementations change and break functionality that this is detected during build/testing on the relavent platforms?

**Comment by grahamehorner** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/410#issuecomment-294364420

**Comment by grahamehorner** [comment]
Seems to be a number of issues with.net core and redid currently across the platforms so we are looking at using sql server caching as a interim solution to avoid this being a blocker for us.

**Comment by muratg** [comment]
This bug got stale so closing it. Please reactivate or file a new bug if you're still having issues.
