### ISSUE TITLE
Calling RedisCache GetAsync fails on second call in ViewComponent that is rendered in PartialView

### ISSUE THREAD

**Issue by rangp** [aspnet/Caching#293]
I just encountered a weird bug that was hard to isolate, but it seems that the redis implementation of IDistributedCache becomes trapped in a deadlock when `GetAsync` is called in a `ViewComponent` that is rendered from a `PartialView`, not on the first call but on the second. Instead of returning the expected `byte[]` the call will run forever, or at least until the timeout is reached and the connection is aborted. 

Steps to reproduce:
1. app.UseRedisDistributedCache
2. Set any value into the cache
3. Try to access that value in a ViewComponent's `InvokeAsync` method
4. Render the `ViewComponent` in a `PartialView` and render that `PartialView` in a full razor page.
5. Navigate to the page that contains the `PartialView` and reload twice.

On the second reload the timeout should occur. 

I created a demo project to demonstrate the bug (see https://github.com/rangp/RedisCachingBug) After starting the application and reloading once the timeout should happen. Please note that the application expects redis to run on localhost without authentication. However I recreated the bug on an azure environment using an azure redis server with authentication, thus it's not restricted to a local environment.

Also weird: The synchronous method `Get` runs without problems. This is really freaking me out, because I have no clue what the cause of this issue could be. I also tried to run several other asynchronous methods in the same manner, including `HttpClient.GetAsync` etc. but only the redis cache `GetAsync` produces a timeout.

(Edit: I'm running the application on a windows 10 machine and have ran it on an azure web app)

**Comment by JunTaoLuo** [comment]
Looks like you are using Microsoft.Extensions.Caching.Redis.Core which is not a package we release. I took a look at the binaries and the major difference is that we have fixed an issue when connecting to the redis cache https://github.com/aspnet/Caching/pull/266. Can you try Microsoft.Extensions.Caching.Redis 1.1.1 and see if you still reproduce the issue?

**Comment by rangp** [comment]
Thanks for the clarification, this was not clear to me. I just contacted the owner of `Microsoft.Extensions.Redis.Core` and asked him to clarify that this is not an official microsoft release in his package description, since the name is quite confusing.

Changing the package indeed made a difference. Now the bug sometimes occurs on the first call to `GetAsync` not just the second one. It's less deterministic now, but I'm afraid it still appears to be faulty.

**Comment by kimpenhaus** [comment]
I am not 100% sure but I might have stumbled across a similar issue when using `RedisCache` / `IDistributedCache` from within a `TagHelper` which is executed during `RenderPartial`.

This issue only seems to appear inside `Azure-Environment` not when using a local Redis installation.

I was able to trace the problem by remote debugging to down to this function: `Task<byte[]> GetAsync(string key)` 

After calling `GetAsync()` it seems that the entire application hangs until the process is stopped by the server:
 
![bildschirmfoto 2017-04-19 um 14 44 05](https://cloud.githubusercontent.com/assets/575109/25180538/abb281d6-250e-11e7-83f0-c447c8fddc1b.png) 
english translation of the error message is like: `The specified CGI application encountered an error and the server terminated the process.`

From that point on the application is completely unresponsive.

**Comment by rangp** [comment]
Thanks for that, I tested `Html.RenderPartialAsync` on my demo project and it fixes the issue. I took a look at the source code and `Html.RenderPartial` has the same implementation as `RenderPartialAsync` except for calling `result.GetAwaiter().GetResult();`

So it seems that `GetAwaiter().GetResult();` is causing the deadlock, which sort of makes sense. But what I don't get is how only Redis can be affected by that issue? From my understanding `HttpClient.GetAsync` is also establishing an async connection and should be prone to deadlocks as well, just it works fine in `Html.RenderPartial`. 

Weird, but the issue is fixed for me.

**Comment by muratg** [comment]
This bug got stale so closing it. Please reactivate or file a new bug if you're still having issues.

**Comment by ansario** [comment]
@muratg it looks like this is still an issue using IDistributedCache in .NET Core 2.0.

**Comment by smithybc** [comment]
I'm still seeing this issue in Microsoft.Extensions.Caching.Redis 2.0.1, please keep issue open

**Comment by Rudithus** [comment]
Hello,

I too am suffering from this issue. 
Is there any update on this?

**Comment by muratg** [comment]
@Rudithus this issue is closed. Could you please
- Open a new issue
- Explain very clearly what you need help with
- If you think you have found a bug, include detailed repro steps so that we can investigate the problem
