### ISSUE TITLE
Question: RedisCache instanceName publicly settable outside constructor

### ISSUE THREAD

**Issue by aagarwal10** [aspnet/Caching#294]
I am currently using Redis Caching along with SessionMiddleware for distributed caching of Session in my aspnetcore app in a web farm setup.

Now, I want to use the same Redis Cache in my current aspnetcore app to cache some other data in one of my module. 
The problem I have is that InstanceName (or _instance variable inside RedisCache.cs) is only settable via constructor which means I cannot share the same redis connection I created in DI for other purposes (using other instance variable).

Please explain if making _instance variable publicly settable for RedisCache.cs will be any problem in next release or is it totally bad idea  

Thanks a lot,

**Comment by aagarwal10** [comment]
I can fork and make this change if you guys are ok with it. Haven't done it yet.
Please advise

**Comment by danroth27** [comment]
@JunTaoLuo @muratg Can you guys take a look at this one?

**Comment by aagarwal10** [comment]
@danroth27 @JunTaoLuo @muratg - Any update on this, please let me know you want me to do this. I can fork the dev and make the change.

**Comment by muratg** [comment]
@Tratcher thoughts?

**Comment by Tratcher** [comment]
Making _instance publicly settable wouldn't help, you'd be changing it for all consumers. You could just as easily append your own key prefix before calling into the same IDistributedCache instance.

**Comment by aagarwal10** [comment]
@Tratcher -- Is there a way to limit the size of data some can set in the cache using Redis extension from Microsoft? Assume IDistributedCache is used from a controller in AspNet Core.

**Comment by Tratcher** [comment]
Nothing built in. You'd have to wrap the IDistributedCache and filter it manually.

**Comment by aagarwal10** [comment]
Cool, thanks
