### ISSUE TITLE
IDistributedCache and RedisCache are not thread safe

### ISSUE THREAD

**Issue by 1amirjalai** [aspnet/Caching#296]
**IDistributedCache** and **RedisCache** are not thread safe on a high traffic website i got the following error.

```
Timeout performing EVAL, inst: 9, queue: 1448, qu: 0, qs: 1448, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: xxxx
(Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)
```

what should be done?

**Comment by benaadams** [comment]
Related? https://github.com/StackExchange/StackExchange.Redis/issues/611

**Comment by benaadams** [comment]
Timeout doc is here: https://stackexchange.github.io/StackExchange.Redis/Timeouts

**Comment by 1amirjalai** [comment]
no it's related to how redis is initialized

http://gigi.nullneuron.net/gigilabs/setting-up-a-connection-with-stackexchange-redis/
https://docs.microsoft.com/en-us/azure/redis-cache/cache-web-app-howto

**Comment by muratg** [comment]
This bug got stale so closing it. Please reactivate or file a new bug if you think we'll need to do any changes on this repo. Thank you.
