### ISSUE TITLE
MemoryCache doesn't notify expired items added via CreateEntry

### ISSUE THREAD

**Issue by biste5** [aspnet/Caching#298]
When adding entries to [MemoryCache](https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs) only using CreateEntry pattern, then I experience that the notification callback of a item expired is only invoked whenever another object is being requested from cache.
This is inconvenient.

I suspect this is because CreateEntry doesn't call `StartScanForExpiredItems();` as other methods (e.g. SetEntry) do.

**Comment by JunTaoLuo** [comment]
How are you using the `CreateEntry` method? The pattern isn't intuitive but the expected usage is as illustrated in https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs#L42-L44

The call to `Dispose()` is what actually adds the entry to the cache which in turn calls `SetEntry`. That should kick off a scan for expired entries.

**Comment by JunTaoLuo** [comment]
There were discussions on revisiting the MemoryCache design here: https://github.com/aspnet/Caching/issues/289

**Comment by biste5** [comment]
Thanks, I've found also a related discussion, with some hings, on SO
https://stackoverflow.com/questions/42535408/net-core-memorycache-postevictioncallback-not-working-properly/42536192

**Comment by JunTaoLuo** [comment]
The comments on SO are correct. Closing issue for now, feel free to re-open if there are further issues. Thanks!
