### ISSUE TITLE
Getting resolution error when trying to dotnet build

### ISSUE THREAD

**Issue by ferrx** [aspnet/Caching#307]
My environment: Windows 7 Pro SP1

Procedures:
1) `git clone` -- good
2) `dotnet restore` -- good
3) `dotnet build` -- errors like:

>   Errors in SqlServerCacheConcurencySample.csproj Unable to resolve 'Microsoft.Extensions.FileProviders.Physical (>= 2.0.0-preview2-25160)' for '.NETFramework,Version=v4.6'.

I see the same errors listed in the currently failing AppVeyor build for the repo at https://ci.appveyor.com/project/aspnetci/caching/build/1.0.916#L267

**Comment by JunTaoLuo** [comment]
This should have been an occasional problem which is encountered when we were pushing packages to the myget feed. If you clear your caches and restart the build it should succeed.
