### ISSUE TITLE
[Enhancement] MemoryCache should have an UpdateCallback like System.Runtime.Caching.MemoryCache

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Caching#31]
I couldn't find in the new implementation of MemoryCache an UpdateCallback like the one in System.Runtime.Caching.MemoryCache.

http://referencesource.microsoft.com/#System.Runtime.Caching/System/Caching/MemoryCache.cs,124

I find this feature extremely useful for those scenarios where you want to repopulate the cache when it expires and you do not want the next request to pay the performance hit.

**Comment by Tratcher** [comment]
Would RegisterPostEvictionCallback handle this?
https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Cache.Memory/ICacheSetContext.cs#L58

**Comment by epignosisx** [comment]
Ahh there it is. Yup, that works!

**Comment by epignosisx** [comment]
On second thought the new API does not implements a use case covered by the Runtime.Caching.MemoryCache.

If I understand correctly that PostEviction callback it's called once the entry has been removed from the cache whereas the UpdateCallback of the Runtime.Caching.MemoryCache runs before the entry is removed from the cache.

The UpdateCallback gives you the opportunity to refresh the cache entry before removing it, allowing the app to read the stale cached entry in the meantime.

**Comment by epignosisx** [comment]
Hi @Tratcher. Any update on this?

**Comment by Tratcher** [comment]
The design is intended.  We wanted to avoid running any user code while holding the data structure locks. We also want changes to a value to trigger eviction on dependent keys. Updating in place confuses the dependency scenario.
