### ISSUE TITLE
Question: Max memory

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Caching#319]
If I use the MemoryCache on an 64-bit environment is there any upper limit of memoryusage other then the physical memory on the server?

If I have 50 or 100 GB as the physical memory limit on the server, will that work without problem for the cache or garbage collection?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
