### ISSUE TITLE
is there a similar project for asp.net(.Net Framework.)

### ISSUE THREAD

**Issue by huoxudong125** [aspnet/Caching#344]
I want to use this function in asp.net Web API 2 , is there a similar project ?

**Comment by davidfowl** [comment]
Caching isn't tied to ASP.NET Core.

**Comment by huoxudong125** [comment]
@davidfowl  I don't want introduce dotnet core in asp.net project.

**Comment by Tratcher** [comment]
The projects like Microsoft.Extensions.Caching.Memory cross target .NET and .NET Core. Try it.

**Comment by Swellenator** [comment]
I've used this in a full .Net 4.6.1 project. There are issues with assembly binding that you get whenever you reference a .Net Standard project but it does work.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
