### ISSUE TITLE
How to get cache size in .net core?

### ISSUE THREAD

**Issue by cex-pnaik** [aspnet/Caching#345]
My application is in .net core pointing to framework 1.1.1. I am using in-memory caching. After setting data in cache, I need to know the cache size. Can someone please tell me, how can this be done?

**Comment by Tratcher** [comment]
This count is not part of the public contract because it is very unstable, it can change at any moment even without a user action. [Count](https://github.com/aspnet/Caching/blob/rel/1.1.2/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L71) is available for testing purposes if you downcast IMemoryCache to MemoryCache.

Or were you referring to total memory size?

**Comment by MaklaCof** [comment]
Stable or not, it would be great to have option to check how many memory cache uses. Together with SignalRCore developers can build admin panel, where administrator could see memory usage graph.
If all the time 100% memory is used, system administrator can increase [memory size limit](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycacheoptions.sizelimit?view=aspnetcore-2.0#Microsoft_Extensions_Caching_Memory_MemoryCacheOptions_SizeLimit). _(By the way is this size in bytes?)_

**Comment by JunTaoLuo** [comment]
The `Count` property is exposed on the downcasted MemoryCache and represents the number of entries in the cache. Size is a concept that was more recently added but the total size of the cache is not publicly exposed so you do not have access to it. The definition of size (whether it's bytes or any other form of measurement) is determined by you. You indicate a size limit on the cache as well as the size of each entry during insertion.  

The best way of determining whether the cache is using too much memory is to register eviction callbacks on the cache entries via https://github.com/aspnet/Caching/blob/45d42c26b75c2436f2e51f4af755c9ec58f62deb/src/Microsoft.Extensions.Caching.Abstractions/CacheEntryExtensions.cs#L105 and examining the `EvictionReason`.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
