### ISSUE TITLE
CancellationToken added to 2.0 IDistributedCache breaks 1.0 based cache implementations

### ISSUE THREAD

**Issue by jeffrymorris** [aspnet/Caching#347]
Hi All -

This[ commit ](https://github.com/aspnet/Caching/commit/eae4e40bc29044427ca4944067213f426aa36116) adds cancellation tokens to some of IDistributableCache members, which causes a MissingMethodException when a 1.0 based implementation is used in a 2.0 project. See [here](https://forums.couchbase.com/t/idistributedcache-missing-method-exception/) for reference.

The question I have is why make the change a breaking change? Why not leave GetAsync(key) and add the second overload that takes cancellation tokens?

Thanks,
Jeff

**Comment by Tratcher** [comment]
Even adding a new overload to the interface would have been a breaking change.

**Comment by jeffrymorris** [comment]
@Tratcher - true, but since its dynamically invoked vs compiled it shouldn't it resolve?

**Comment by Tratcher** [comment]
It depends on how it was called, among other things. The issue is moot at this point though because the 2.0 bits have been finalized.
