### ISSUE TITLE
DistributedCacheEntryOptions generate a hash type value.

### ISSUE THREAD

**Issue by WHATSAF** [aspnet/Caching#358]
When i call the `setstring()` with the parameter `DistributedCacheEntryOptions`, it will generate a hash type value.Because of that, when i call the `stackexchange.redis.getstring()` of the .Net Framework's version, it will throw a exception like `"wrong type value"`.

**Comment by Tratcher** [comment]
Please show the actual code. I don't understand what you're doing.

**Comment by WHATSAF** [comment]
@Tratcher 
`await _cache.SetStringAsync(userInfo.SessionId, JsonHelper.ToJson(userInfo), new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(_options.SessionTimedout)
            });`
This is the code in the .net core project.
`public string GetString(string key)
        {
            return db.StringGet(_nameSpace + key);
        }
`
And this is the code use the `StackExchange.Redis.StrongName`, it will throw a excption because the `SetStringAsync()` method above will set a hash type in redis.Should i use the `db.HashGet()` method ?

**Comment by Tratcher** [comment]
DistributedCache only stores `byte[]` instances, strings are converted to utf8 first and some expiration metadata is appended. The redis string apis are not used. The DistributedCache values are not intended to be accessed directly from the underling store, only through the same API.

**Comment by WHATSAF** [comment]
Thanks, i understood.
