### ISSUE TITLE
Expose more functions like TTL for Redis

### ISSUE THREAD

**Issue by jasondaicoder** [aspnet/Caching#363]
Hi guys,

Do we have any plans to expose more functionalities like TTL command for Redis via the IDistributedCache interface or some other way?

Thanks

Jason

**Comment by Tratcher** [comment]
Per entry options? No.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
