### ISSUE TITLE
SqlServerCache does not pass on CancellationToken

### ISSUE THREAD

**Issue by jovnas** [aspnet/Caching#365]
This might be by design, but the following lines does not pass on the supplied token and will therefor use default(CancellationToken) instead.

https://github.com/aspnet/Caching/blob/be34c214c2fd1a9557c97bb3f4ff5416df941bd0/src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs#L112

https://github.com/aspnet/Caching/blob/be34c214c2fd1a9557c97bb3f4ff5416df941bd0/src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs#L140

https://github.com/aspnet/Caching/blob/be34c214c2fd1a9557c97bb3f4ff5416df941bd0/src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs#L166

https://github.com/aspnet/Caching/blob/be34c214c2fd1a9557c97bb3f4ff5416df941bd0/src/Microsoft.Extensions.Caching.SqlServer/SqlServerCache.cs#L220

**Comment by muratg** [comment]
Yeah, looks like a bug to me (@Tratcher do you agree?)

We would accept a PR for this.

**Comment by Tratcher** [comment]
Yes, it's worth a try.

**Comment by muratg** [comment]
Thanks @jovnas for the contribution!
