### ISSUE TITLE
MemoryCache Compact doesn't remove items for low percentage

### ISSUE THREAD

**Issue by amit-ezra** [aspnet/Caching#370]
If you explicitly run  `public void Compact(double percentage)` and your percentage calculation is less than 1 item, the Compact method will round it down to zero, and no items will be removed. 
e.g. 
Count = 10
Percentage = 0.05 (the default CompactionPercentage)

no items will be removed. IMO at least a single item should be removed.
this is rooted in the following code (MemoryCache.cs)
`int removalCountTarget = (int)(_entries.Count * percentage);`

(int) will round down any number lower than 1. 
I think either `Math.Ceiling` can be used, or even better, to keep exiting behavior similar, 
`int removalCountTarget = Math.Max(1,(int)(_entries.Count * percentage));`

Thanks!
Amit

**Comment by Tratcher** [comment]
That would only make sense if the result was anywhere close to 1 already. e.g. should 1% remove 1 of 10 items (10%)? Should 25% remove 1 of 1 items (100%)?

This is a mute point though. How many items do you normally expect to store in the cache? More than 20 I'd guess, so 5% would already remove at least one.

**Comment by amit-ezra** [comment]
I understand your point, though IMO it doesn't matter how close it is. and it's true that if you are using a large enough cache, the issue won't manifest, but it's still hidden there.
I still think the expected behavior is to remove a single item as long as the percentage > 0

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
