### ISSUE TITLE
Redis 4.* compatibility

### ISSUE THREAD

**Issue by danbarua** [aspnet/Caching#376]
StackExchange.Redis 1.2.4 is unable to connect to Redis clusters running version 4.*
This is fixed by updating to StackExchange.Redis 1.2.6

**Comment by danbarua** [comment]
https://github.com/antirez/redis/issues/4186

**Comment by danbarua** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/672

**Comment by dmwharris** [comment]
Following this thread, I'm still not able to connect to my cluster, though my code may be incorrect.  Using Client 1.2.6 to server 4.0.8

string ip="172.16.150.71:6379,172.16.150.72:6379,172.16.150.73:6379,172.16.150.74:6379,abortConnect=false";

ConfigurationOptions config = ConfigurationOptions.Parse(ip);
var connectVal = ConnectionMultiplexer.Connect(config);
IDatabase dbVal = connectVal.GetDatabase(0);
CommandFlags = CommandFlags.None;
RedisValue[] art_typs = dbVal.SetMembers("for_art_typs",flags);

Error is "No connection is available to service this operation: SMEMBERS for_art_typs; Value cannot be null. Parameter name:key'

From redis-cli, I know "for_art_typs" is @ 172.16.150.72 and "keys for*" returns the set.

I've tried the following variations on this code and get the same error above:
ip="172.16.150.71:6379@16379,172.16.150.72:6379@16379,172.16.150.73:6379@16379,172.16.150.74:6379@16379,abortConnect=false";
ip="172.16.150.71,172.16.150.72,172.16.150.73,172.16.150.74,abortConnect=false";

Also tried the following and get the same error above:

ConfigurationOptions options = new ConfigurationOptions
{
   KeepAlive=0,
   AllowAdmin=true,
   AbortOnConnect=false,
   EndPoints = { {"172.16.150.71:6379"},
                          {"172.16.150.72:6379"},
                          {"172.16.150.73:6379"},
                          {"172.16.150.74:6379"}}
};
var connectVal = ConnectionMultiplexer.Connect(options);
IDatabase dbVal = connectVal.GetDatabase(0);
CommandFlags = CommandFlags.None;
RedisValue[] art_typs = dbVal.SetMembers("for_art_typs",flags);

**Comment by muratg** [comment]
@glennc

**Comment by muratg** [comment]
This is done: https://github.com/aspnet/Caching/blob/master/build/dependencies.props#L21
