### ISSUE TITLE
Use MemoryCache Inside ConfigureServices Method

### ISSUE THREAD

**Issue by stumpykilo** [aspnet/Caching#384]
How would I use MemoryCache inside the ConfigureServices method? I want to access the MemoryCache when I call AddDbContext and set the connection string. This is a .NET Core 2.0 Web Api project that needs to dynamically set the connection string after authenticating with a JWT token.

**Comment by bricelam** [comment]
Just call `.AddDbContext<MyContext>()` in startup, then override `DbContext.OnConfiguring()` to make the appropriate `UseSqlServer()` call. You should be able to inject the cache into the DbContext's constructor.

**Comment by bricelam** [comment]
You may also need to call `AddEntityFrameworkSqlServer()` in addition to `AddDbContext()` in `ConfigureServices()`

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
