### ISSUE TITLE
Add Redis ConfigurationOptions to RedisCacheOptions

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Caching#389]
Issue to track the feature added in https://github.com/aspnet/Caching/pull/388. 

We want to add a `ConfigurationOptions` property on `RedisCacheOptions` so that options that cannot be expressed as a connection string such as `RemoteCertificateValidationCallback` can be set when creating a connection. `ConfigurationOptions` will take priority over existing `Configuration` string.

**Comment by JunTaoLuo** [comment]
Completed via https://github.com/aspnet/Caching/pull/388. Thanks @TroyCornwall !

**Comment by TroyCornwall** [comment]
I think this also closes #375 👍

**Comment by cod7alex** [comment]
nice!
