### ISSUE TITLE
Update redis dependency [2.0]

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Caching#397]
From email discussions, we should update the dependency from 1.2.4 to 1.2.6. I'm filing the issue here for tracking but the update will be made in Universe. This issue tracks the update in release/2.0.

cc @muratg

**Comment by JunTaoLuo** [comment]
@muratg will we be patching 2.0, and 1.x as well for August? If so, we should fix this as well.

**Comment by muratg** [comment]
@leecow is August 2.1.x only? Or is 1.x and 2.0.x covered as well?

**Comment by leecow** [comment]
All versions from what I can tell.

**Comment by JunTaoLuo** [comment]
Not patching for this. Users can workaround this by specifying the updated version.
