### ISSUE TITLE
RemoveAsync not working with Azure RedisCache backed IDistributedCache?

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/Caching#435]
I am using an IDistributedCache, backed by Azure Redis Cache (services.AddDistributedRedisCache)
It appeared to be working nicely... until I found today that after calling await RemovAsync, the removed key and it's content where still in the cache instance! Is this a known issue?

**Comment by Tratcher** [comment]
No, that's a new one.
- What package versions are you using?
- How did you confirm the data was still in the cache? Can it still be retrieved via GetAsync?
- How consistently does it repro?
- Can you repro it with a local redis instance?
