### ISSUE TITLE
Microsoft.Framework.Expiration.Interfaces namespace has just one type

### ISSUE THREAD

**Issue by Eilon** [aspnet/Caching#61]
The `Microsoft.Framework.Expiration.Interfaces ` namespace has just one type: `IExpirationTrigger`

https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Abstractions/IExpirationTrigger.cs#L6

And what a weird namespace name, too.

it appears to be used within caching, and also within the FileSystem repo to implement the file watcher notifications, e.g.:
* [NoopTrigger](https://github.com/aspnet/FileSystem/blob/bf092bc5f10d38de03200c7d68b35596d86fe9fd/src/Microsoft.AspNet.FileProviders.Common/Implementation/NoopTrigger.cs#L9)
* [IFileProvider](https://github.com/aspnet/FileSystem/blob/7f693ac5cf4ad8b8a3c097cb55b196570fca673e/src/Microsoft.AspNet.FileProviders.Abstractions/IFileProvider.cs#L32)

I don't have a specific suggestion on what it should be, but I don't think it can stay as is. Perhaps it goes to the main Caching namespace? (And we get rid of the unnecessary `.Interfaces` namespace suffix as well.)

**Comment by muratg** [comment]
Agreed, this interface should stay in Abstractions assembly, and the namespace should be `Microsoft.Framework.Caching`

**Comment by kichalla** [comment]
commit fa8f9772271bf20c1697f762c579c2799cd79149
