### ISSUE TITLE
Missing ServiceCollection extension method for Redis cache 

### ISSUE THREAD

**Issue by unaizorrilla** [aspnet/Caching#63]
Why not exist extension method on ServiceCollection to register RedisCache?

**Comment by Eilon** [comment]
I think the reason is quite simple: because no one added it :smile:

**Comment by unaizorrilla** [comment]
Hi Elion! 
Accept contribution on this topic?

Thanks 
Unai

**Comment by Eilon** [comment]
Well, I *think* it makes sense to have such a helper extension method (it's probably just 2-3 lines of code, but still).

Adding @HaoK @Tratcher to check if they agree it makes sense.

**Comment by HaoK** [comment]
Yeah probably AddRedis()?

**Comment by unaizorrilla** [comment]
AddRedis or AddRedisCaching?

**Comment by Eilon** [comment]
`AddRedisCache` maybe? That matches the singular name that's used elsewhere in the Redis stuff.

**Comment by unaizorrilla** [comment]
Ok for me!

**Comment by kichalla** [comment]
commit a8790019715bca25555238ef4a792960d3ca1e4c
