### ISSUE TITLE
Key for memory cache should be of type object instead of string

### ISSUE THREAD

**Issue by divega** [aspnet/Caching#67]
There doesn't seem to be a good reason for it to be constrained to string and object could have a number of advantages, e.g.:

- Perf: no need to compute a string based on individual components
- Easier to avoid collisions by having separate key types
- Potentially easier to add (and read) metadata to (from) the key
- Encapsulation: cache key can be made non-public, forcing other components to not sniff directly into the cache but talk to the right layer

cc @lodejard @davidfowl and @anpete

**Comment by Eilon** [comment]
Interesting... :bulb:
