### ISSUE TITLE
Multiple Redis cache instances

### ISSUE THREAD

**Issue by ehabelgindy** [aspnet/Caching#76]
Is it possible to create multiple instances of the RedisCache class where each instance connects to a different server/instance of Redis?

As far as I can see that the RedisCache class doesn't support named options, hence I presume that all instances have to use the same configuration.
Thanks

**Comment by Tratcher** [comment]
You should be able to do multiple instances if you create them directly:
`new RedisCache(new RedisCacheOptions() {...});`

**Comment by ehabelgindy** [comment]
I thought so, probably this is the reason why the RedisCacheOptions implements the IOptions<RedisCacheOptions>.

This raises the question of how to new up multiple SqlServerCache instances with different options?
NB: the SqlServerCacheOptions class doesn't implement the IOptions<...> (Issue #75)

**Comment by muratg** [comment]
Closing this one and keeping the SQL Server one for triage.
