### ISSUE TITLE
Microsoft.Framework.Caching.Abstractions package description is incorrect

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Caching#78]
https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Abstractions/project.json#L5

"ASP.NET 5 <b>in memory</b> cache abstractions."

As there is now a SqlServerCache, this package can not be said as "in memory" abstraction.

**Comment by muratg** [comment]
Feel free to squeeze this in with test changes :)

**Comment by BrennanConroy** [comment]
Fixed in #100
