### ISSUE TITLE
IDistrbutedCache Extension Methods/Helper Methods

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Caching#79]
The IDistrbutedCache seems pretty basic at the moment compared to the IMemoryCache, as it only deals in byte arrays. Most developers using this interface will be writing some extensions methods for it. 

This [StackOverflow post](http://stackoverflow.com/questions/31458950/is-there-any-guidance-for-caching-patterns-in-asp-net-5) is asking if these methods will eventually be part of ASP.NET Caching or if we should role our own.

The ```BinaryFormatter``` is not available in .NET Core, is it going to be added in future? In the mean time the ```BinaryWriter``` and ```BinaryReader``` seem to be the way to go. I might just submit a pull request this evening.

See the StackOverflow post for the proposed extension methods.

**Comment by RehanSaeed** [comment]
I created a pull request (https://github.com/aspnet/Caching/pull/94) to help provoke a discussion about the best way forward.

**Comment by muratg** [comment]
Closing this based on https://github.com/aspnet/Caching/pull/94#discussion_r39995622
