### ISSUE TITLE
Any Plans to Implement VaryByParam?

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Caching#86]
Are there any plans to implement the MVC 5 ```VaryByParam``` property on ```ResponseCache``` and ```CacheProfile```?

**Comment by RehanSaeed** [comment]
I think this should be asked in the MVC project.

**Comment by Tratcher** [comment]
The kernel mode cache in IIS and WebListener is not capable of supporting any vary-bys. It could be supported in a middleware: https://github.com/aspnet/responsecaching

**Comment by barbarosalp** [comment]
- Custom middleware 
- Read querystring or something else 
- Cache it with IMemoryCache.
