### ISSUE TITLE
Add a new net45(1) target for the Redis provider

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Caching#87]
The Redis provider is the only one that doesn't target `net45`. That would be great if we could fix that :smile: 

https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Redis/project.json#L15

**Comment by davidfowl** [comment]
@PinpointTownes what for?

**Comment by PinpointTownes** [comment]
1. consistency.
2. being able to use the Redis provider outside DNX :smile:

**Comment by kichalla** [comment]
935778577e4542327231f9ea147203519798975c

**Comment by davidfowl** [comment]
@kichalla this needs to be marked as done

**Comment by kichalla** [comment]
Done @davidfowl :smile:
