### ISSUE TITLE
Access Cache globally in ASP.NET 5

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Caching#88]
Hello,
In ASP.NET 4, we can always get Cache instance by using HttpContext.Cache.
What's the similar solution for me to get this kind of global cache access in all my Controllers and Middlewares  in ASP.NET 5?

Thanks lot
Gary

**Comment by Tratcher** [comment]
You should use dependency injection for this. See the Session middleware and samples:
https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L37-L39
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/SessionServiceCollectionExtensions.cs#L23
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/DistributedSessionStore.cs#L17
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/SessionMiddleware.cs#L39
You can also access the services directly: `HttpContext.ApplicationServices.GetRequiredService<IMemoryCache>()`

**Comment by davidfowl** [comment]
We recommend constructor injection where possible. Avoid `HttpContext.ApplicationServices.GetRequiredService<IMemoryCache>()` if possible

**Comment by PrimeObjects** [comment]
I added services.AddCaching(); to my ConfigureServices function in startup.cs
 public void ConfigureServices(IServiceCollection services)
 {
             services.AddApplicationInsightsTelemetry(Configuration);

            services.AddCaching();
            services.AddSession();
            services.AddMvc();

            services.AddInstance<IConfiguration>(Configuration);
            
 }

What should I do to the constructor of Controller?

Or how can I access global Cache in all my Controller?

**Comment by Tratcher** [comment]
@rynowak?

**Comment by kichalla** [comment]
Examples:
- Injecting into constructor 
`public ProductsController(IMemoryCache cache)`

- Injecting into controller's action(`FromServices` is specific to Mvc only)
`public Task<IActionResult> Details(int id, [FromServices] IMemoryCache cache)` 

- Injecting into controller's property
  ```
  [FromServices]
  public IMemoryCache Cache { get; set; }
  ```

Regarding using `[FomServices]` vs constructor injection: For example, if I have only one action which uses cache, then probably prefer `[FomServices]` on the action directly as its easier on unit testing.

**Comment by PrimeObjects** [comment]
Thank you very much!
