### ISSUE TITLE
Where's is the simple TSQL script for creating the CacheTable

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Caching#92]
Hi team,
There's a TableName parameter to define the table used by SQLCache.
I searched online, it seems I have to call DNX commands somehow to create tables. and there's other document about how to make DNX ready. I think it is too complex and unnecessary. 
I guess the script for table (maybe some stiredprocedures and triggers) must be very straightforward. could you provide the whole TSQL for creating the table and other database objects in a file on github? So developers can simply run it by themselves?

Cheers
Gary

**Comment by kichalla** [comment]
Have you looked at this : https://github.com/aspnet/Announcements/issues/43

**Comment by PrimeObjects** [comment]
I did, I'm using VS2015 and don't have dnu in my dos command window, and according to the link below there are different steps to run DNX so I can run dnu (correct if I'm wrong here)

http://blogs.msdn.com/b/sujitdmello/archive/2015/04/23/step-by-step-installation-instructions-for-getting-dnx-on-your-laptop.aspx

My questions is it easier for developer just run whatever the TSQL you are using in the command directly on SQL Server?  I guess it is going to create one table and a few indexes. It should be a easy run right?

Why not just put the TSQL on the source control.?

**Comment by PrimeObjects** [comment]
Hi friends, Any progress on this?

**Comment by kichalla** [comment]
We currently do not have separate tsql files which setup the table and indexes. But you can take a look at the following: https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.SqlConfig/SqlQueries.cs

**Comment by PrimeObjects** [comment]
The SQL statement works. However I changed nvarchar(900) to varchar(450)
CREATE TABLE _AspNetCache(
Id varchar(450)
